### ISSUE TITLE
getkeypool should `--keypool` by default?

### ISSUE THREAD

**Issue by instagibbs** [bitcoin-core/HWI#136]

**Comment by jb55** [comment]
I believe this has key reuse implications? What core probably needs is a way to semi-intelligently import keys to the keypool or not based on if they have any transaction associated with them, if I'm understanding the purpose of keypool correctly...

**Comment by jb55** [comment]
some more context from @achow101 since I didn't realize the subtleties of keypool imports:

```
#bitcoin-core-dev
21:56 <jb55> achow101: will core re-use keypool-imported addresses if they've been used already? if not then there's no issue.
21:57 <achow101> jb55: only if you rescan after importing
21:57 <achow101> rescanning will remove used things from the keypool
```

it seems currently core will only remove used keys from the keypool on the next rescan, not on the initial one.

**Comment by Sjors** [comment]
There is no rescan when you import keys using the instructions in this repo. You have to call rescan yourself. At that point used keys are removed from the keypool.

**Comment by jb55** [comment]
if that's the case then :+1: for keypool default. will verify...

**Comment by instagibbs** [comment]
this continues to mess me up, we should really do this
