### ISSUE TITLE
Error parsing JSON

### ISSUE THREAD

**Issue by nopara73** [bitcoin-core/HWI#145]
I followed the tutorial on my coldcard and it did not succeed to do `importmulti`.

https://github.com/bitcoin-core/HWI/blob/master/docs/bitcoin-core-usage.md

```
hwi --testnet -f 7a88e7a2 getkeypool --wpkh --keypool 0 1000
[{"desc": "wpkh([7a88e7a2/84h/1h/0h]tpubDC7pT42Gr8ox24agqaaKnYHkcapDcaeRiQLwxiv91TxBWxuCdp8LHsuTiQqHqrCXNb8jjCMztw6aZsYokYbAYjdCbunBk2E2DDTqtDUw1s4/0/*)#caxltj90", "range": [0, 1000], "timestamp": "now", "internal": false, "keypool": true, "watchonly": true}]

bitcoin-cli.exe --testnet -rpcwallet=coldcard importmulti '[{"desc": "wpkh([7a88e7a2/84h/1h/0h]tpubDC7pT42Gr8ox24agqaaKnYHkcapDcaeRiQLwxiv91TxBWxuCdp8LHsuTiQqHqrCXNb8jjCMztw6aZsYokYbAYjdCbunBk2E
2DDTqtDUw1s4/0/*)#caxltj90", "range": [0, 1000], "timestamp": "now", "internal": false, "keypool": true, "watchonly": true}]'
error: Error parsing JSON:[{desc: wpkh([7a88e7a2/84h/1h/0h]tpubDC7pT42Gr8ox24agqaaKnYHkcapDcaeRiQLwxiv91TxBWxuCdp8LHsuTiQqHqrCXNb8jjCMztw6aZsYokYbAYjdCbunBk2E2DDTqtDUw1s4/0/*)#caxltj90, range: [0, 1000], timestamp: now, internal: false, keypool: true, watchonly: true}]
```

### Environment

TestNet, Windows 10, tried to use both `cmd` and `PowerShell`.

**Comment by instagibbs** [comment]
Can you figure out importmulti on your environment? Try importing anything?

**Comment by Sjors** [comment]
Most likely bitcoin-cli is being picky about how you escape JSON, though it looks correct (minus the linebreak, but that's probably just on Github).

**Comment by ryanofsky** [comment]
You can't use single quotes to delimit arguments with normal windows command line (not sure about powershell). You probably need need to replace `'` with `"` before and after the argument and replace and `"` with `""` internally. There's more information at https://stackoverflow.com/questions/7760545/escape-double-quotes-in-parameter and you can experiment with `bitcoin-cli echo`.

**Comment by nopara73** [comment]
@ryanofsky Thanky you! Your suggestion was on-point, though the solution din't work.  

`bitcoin-cli echo` was useful, so I figured I have to encapsulate it with `"` instead of `'` and escape out all the `"` with a `\` inside. So like this: `hwi.exe "foo\"bar"` which would result in an argument `foo"bar`.

**Comment by FontaineDenton** [comment]
For any newbs out there lie me this is what I had to do: 

```
bitcoin-cli -rpcwallet=NewTest importmulti '[{ "desc": "wpkh([18734cbe/84'"'"'/0'"'"'/0'"'"']xpub6AC5B4KkrtMkXmzUWAiVVYWvhzwMJDX46ZJhm2tusm7SPc2KjeSqwEjLTaB8vAo7ev3zUFbGdWcX3EMy1ZQ9JxDgpc1pzBGLVpftq84naq5/0/*)#jun2ynxt", "timestamp": "now", "range": [0, 99], "watchonly": true, "label": "Fully Noded Cold Storage", "keypool": true, "internal": false }]' '{"rescan": false}'
```
