### ISSUE TITLE
Ubuntu: No module named pkg_resources

### ISSUE THREAD

**Issue by Sjors** [bitcoin-core/HWI#148]
On a Ubuntu 18.04 machine I installed Poetry using the magic albeit scary incantation [here](https://github.com/sdispater/poetry#installation). 

```
poetry install

[ImportError]
No module named pkg_resources

install [--no-dev] [--dry-run] [-E|--extras EXTRAS] [--develop DEVELOP]
```

**Comment by Sjors** [comment]
I had to make Python 3 the default on the system (`sudo update-alternatives --install /usr/bin/python python /usr/bin/python3.6 1`). Then it throws another, but more informative error:

```
$ poetry install
Creating virtualenv hwi-py3.6 in /home/dev/.cache/pypoetry/virtualenvs
The virtual environment was not created successfully because ensurepip is not
available.  On Debian/Ubuntu systems, you need to install the python3-venv
package using the following command.

    apt-get install python3-venv

You may need to use sudo with that command.  After installing the python3-venv
package, recreate your virtual environment.

Failing command: ['/home/dev/.cache/pypoetry/virtualenvs/hwi-py3.6/bin/python', '-Im', 'ensurepip', '--upgrade', '--default-pip']
```

**Comment by Sjors** [comment]
`sudo apt-get install python3-venv`, erasing `~/.cache` and then running `poetry install` again seems to do the trick.

**Comment by trr-RodriguesJD** [comment]
@Sjors That didn't work for me.

**Comment by jlopp** [comment]
@Sjors I ran into the same issue on PureOS, though I fixed it by:

1. Changing my symbolic link /usr/bin/python to point to /usr/bin/python3.7
2. Only had to rm -rf ~/.cache/pypoetry

**Comment by achow101** [comment]
Is this still an issue?

**Comment by Sjors** [comment]
I haven't tried this in ages.
