### ISSUE TITLE
Can't retain passphrase state on Trezor T

### ISSUE THREAD

**Issue by matejcik** [bitcoin-core/HWI#151]
This is actually two closely related issues. Both are on a Trezor T with default config and passphrase enabled.

Unlike Trezor One, TT has the ability to enter passphrase on device. So HWI's method of passing `--password` argument doesn't work. Instead, every time you perform a password-protected action, the device shows a pop-up asking for the passphrase.

Issues:
1. When you run any action (e.g., `hwi displayaddress`), you are asked for the passphrase twice.
This is because you don't retain passphrase state between actions.
you are supposed to do something like
```python
# in enumerate():
saved_state = client.client.state
# in TrezorClient.__init__:
self.client = Trezor(..., state=saved_state)
```
2. You can't retain passphrase state across runs. So if some software used hwi to do several actions, they'd be swamped with passphrase pop-ups.
Not sure what the solution is here. If the CLI is stateless, then presumably you'd need a `get-passphrase-state` command and then allow supplying that on repeated runs, sort of what you do with `prompt-pin`/`send-pin`

**Comment by achow101** [comment]
Hmm. I thought that passphrases would be cached by the device, given that one of the fields in a `Features` message is `passphrase_cached`. I don't suppose there's a way to make it cache the password?

Is it possible to have the passphrase passed to the device as we do for the Trezor One?

**Comment by matejcik** [comment]
> Hmm. I thought that passphrases would be cached by the device, given that one of the fields in a `Features` message is `passphrase_cached`. I don't suppose there's a way to make it cache the password?

It does that, but only within a single "session". You're creating at least two. You need the `state` field passed to `Initialize` to indicate that you're doing the same session as before.

> 
> Is it possible to have the passphrase passed to the device as we do for the Trezor One?

By default TT asks if you want to input on host or on device. If you tap "host", it uses what the PC supplied. And you can configure it so that it chooses "host" instead of asking. So that's a work-around.
But entering passphrase on device is a rather important security feature, so.

**Comment by achow101** [comment]
> It does that, but only within a single "session". You're creating at least two. You need the state field passed to Initialize to indicate that you're doing the same session as before.

Ah, I see.

One possibility would be to never let the session end. It would just be that on close we don't close the session and on initialize, we check whether the session is open before sending `Initialize` (similar to what `promptpin` and `sendpin` do). However that may be unsafe since we release the USB handle but let the session remain open.

**Comment by achow101** [comment]
@matejcik Would it be okay to just never send an `Initialize` message? Would that cause any problems?

**Comment by matejcik** [comment]
It would make it more fragile. But as long as HWI is the only user of Trezor, and as long as all flows are properly completed, it would work.
(that is of course until we implement true session handling, but that's in the distant future)

**Comment by achow101** [comment]
Is there some way to and unset a bit? Or maybe non-persisted counter? I was thinking of setting a flag once a command begins and unset it when the command completes. If the action aborts in the middle, the flag will be set which indicates that `Initialize` should be sent the next time the client is opened. If not set, then no `Initialize` is sent and the session remains open. A counter would work just as well.

I was going to use `ApplyFlags` to do this but I realized that it cannot unset bits and it appears to be persistent, so it isn't usable for this.

**Comment by matejcik** [comment]
the main problem with this is that the inconsistent states where you need to initialize are the same inconsistent states where you wouldn't be able to read the bits
IOW if the device is good enough for `GetFeatures`, it's good enough to just do what you need in the first place
