### ISSUE TITLE
Handle when user is not in the Bitcoin app on Ledger Nano S

### ISSUE THREAD

**Issue by achow101** [bitcoin-core/HWI#158]
We need to make sure that we give a proper error when the user is not in the Bitcoin app on the Ledger Nano S. I was unable to find a way to  detect this. It seems like what happens is that there's just an error that gets thrown with an unhelpful error message, so maybe we just need to make the error messages better?

@instagibbs Can you take a look?

**Comment by instagibbs** [comment]
sounds like better error codes aren't coming until 1.5 firmware update

**Comment by achow101** [comment]
Looks like some people are running into this: https://github.com/zkSNACKs/WalletWasabi/issues/3931#issuecomment-659412817

Any idea if there are better error codes now or a check we can do?

**Comment by promag** [comment]
Have you tried to exchange "get app name" APDU `cla=0xb0` `ins=0x01`?
