### ISSUE TITLE
trezor enumerate asks to promptpin?

### ISSUE THREAD

**Issue by jb55** [bitcoin-core/HWI#171]
I cloned the latest and tried running enumerate:

```
jb55@quiver> hwi enumerate
[
  {
    "path": "webusb:001:2",
    "type": "trezor",
    "error": "Could not open client or get fingerprint information: Trezor is locked. Unlock by using 'promptpin' and then 'sendpin'."
  }
]
```

so I tried promptpin:

```
jb55@quiver> hwi promptpin
{
  "error": "You must specify a device type or fingerprint for all commands except enumerate",
  "code": -1
}
```

not sure what to do from here

**Comment by achow101** [comment]
You need to specify the device to connect to using the `--device-type` and `--device-path` options. `hwi --device-type trezor --device-path webusb:001:2 promptpin` should work.

**Comment by jb55** [comment]
it says these are optional arguments, should they be marked as required?

**Comment by jb55** [comment]
I think I get it now, nm

**Comment by jb55** [comment]
it looked like that enumeration output was just an error message, I didn't realize it was the expected output for that command.
