### ISSUE TITLE
idea: getkeypools ?

### ISSUE THREAD

**Issue by jb55** [bitcoin-core/HWI#172]
related: #57 #135 

It would be nice to just type getkeypools 0 1000, which would dump all the relevant paths (including change) for that device. in the case of trezor, it needs:

legacy: bip44
p2sh-p2wpkh: bip49 
p2wpkh: bip84

would save a lot of headache for wallet devs looking to integrate hwi

**Comment by instagibbs** [comment]
As a non keypool import option?

**Comment by jb55** [comment]
I guess this is similar to #137 but I was thinking it would have the same output format as getkeypool

**Comment by jb55** [comment]
@instagibbs oh I just realized that would be tricky... you would need a non-keypool import for already used keys wouldn't you. and there may be no way to know which ones have been used ahead of time... hmm

**Comment by jb55** [comment]
I realize now that #137 will be better once we have native descriptor wallets...
