### ISSUE TITLE
[tests] run test_big_tx after test_sign_tx

### ISSUE THREAD

**Issue by Sjors** [bitcoin-core/HWI#179]
It's currently the first test that needs display interaction on the device, yet the most likely to fail.

E.g. rename to `test_sign_big_tx`.

**Comment by instagibbs** [comment]
Is it still failing regularly?

**Comment by instagibbs** [comment]
or do you mean, just do the cheaper signing test first to detect regressions early

**Comment by Sjors** [comment]
> or do you mean, just do the cheaper signing test first to detect regressions early

Indeed.

**Comment by achow101** [comment]
Is signtx actually cheaper than bigtx? It feels like bigtx is faster.

**Comment by instagibbs** [comment]
still an issue?

**Comment by Sjors** [comment]
I haven't tested this in decidecades.
