### ISSUE TITLE
-13 error code BitBox 

### ISSUE THREAD

**Issue by tongokongo** [bitcoin-core/HWI#189]
Trying my DigitalBitbox on RaspberryPi

`$ ./hwi.py enumerate`
`[{"error": "Could not open client or get fingerprint information: Password must be supplied for digital BitBox", "path": "0001:0006:00", "type": "digitalbitbox", "code": -6}]
`

After providing PROPER device password, I am getting UNKNOWN_ERROR = -13
`$ ./hwi.py --password "redacted" enumerate`
`[{"type": "digitalbitbox", "code": -13, "error": "Could not open client or get fingerprint information: open failed", "path": "0001:0006:00"}]
`

For now, I can't test it on my other devices as I don't want to wipe them, but I will this week. Any suggestions if there are any paths I can take to troubleshoot it? Should HWI work out of the box on ARM systems?

**Comment by achow101** [comment]
Have you installed the udev rules?

**Comment by tongokongo** [comment]
Thanks, resolved. I missed the installation step. Can be closed.
