### ISSUE TITLE
trezor: password is ignored when already unlocked

### ISSUE THREAD

**Issue by jb55** [bitcoin-core/HWI#199]
When you unlock a trezor, all future commands will continue to use the unlocked passphrase, even when you pass different passwords.

### To reproduce

```
$ hwi promptpin
$ hwi sendpin
$ hwi --stdinpass enumerate
[{"needs_passphrase_sent": false, "needs_pin_sent": false, "type": "trezor", "path": "webusb:001:11", "fingerprint": "446284ab"}]

$ hwi --stdinpass enumerate # with different password
[{"needs_passphrase_sent": false, "needs_pin_sent": false, "type": "trezor", "path": "webusb:001:11", "fingerprint": "446284ab"}]
```

### Expected result

I would expect to git a different fingerprint if the password is changed, or at least to not re-prompt

**Comment by achow101** [comment]
This is expected behavior. See #152

**Comment by jb55** [comment]
if this is the expected behavior, we should not prompt on --stdinpass, because it has no effect.

**Comment by jb55** [comment]
should make --stdinpass an error, since it's an invalid/no-op option for unlocked trezor devices? otherwise it is super misleading, and could lead to loss of funds (`getkeypool`ing keys which you expect to be in a different bip39 passphrase HD keyset).

another issue: since there's no double-prompt like `trezorctl`, it's pretty easy to unlock into a wrong HD key by accident without realizing it.
