### ISSUE TITLE
trezor: password prompt defaults to empty except on enumerate

### ISSUE THREAD

**Issue by jb55** [bitcoin-core/HWI#200]
Right now it appears (every?) command except `enumerate` unlocks the trezor with an empty passphrase when ran. This is error prone because it's easy to forget --stdinpass.

### To reproduce

```
$ hwi promptpin
$ hwi sendpin
$ hwi enumerate
[{"path": "webusb:001:11", "error": "Could not open client or get fingerprint information: Trezor is locked. Unlock by using 'promptpin' and then 'sendpin'.", "type": "trezor", "needs_pin_sent": false, "needs_passphrase_sent": true, "code": -12}]

$ hwi getxpub "m/1'"
```

`getxpub` will automatically unlock with an empty passphrase.

### Expected result

I would expect the password prompt to return this error message on the `getxpub` command as well: 

```
Could not open client or get fingerprint information: Passphrase needs to be specified before the fingerprint information can be retrieved
```

### Related issues

Once unlocked, --stdinpass will still prompt, but the password input will not change the fingerprint, it still uses the current unlocked fingerprint. see #199

**Comment by achow101** [comment]
This is expected behavior. See #152
