### ISSUE TITLE
trezor: signtx silently fails if we're signing with the wrong fingerprint

### ISSUE THREAD

**Issue by jb55** [bitcoin-core/HWI#201]
I'm not sure who's responsible for this error, if trezor is throwing it but we're not returning it, or if trezor doesn't return an error, I haven't had time to investigate it yet.

I noticed this when I used signtx on some PSBT inputs that were in a BIP39 passworded BIP84 account, but I was using signtx without a passphrase. my trezor prompted me to sign like normal, but it didn't actually sign anything, and returned the unsigned PSBT without any errors.

I eventually got it to sign after working through other issues: #199 #200, but due to the lack of error messages it was really hard to figure out what went wrong.

**Comment by instagibbs** [comment]
Why should the signer complain about wrong fingerprint?

You could argue an error should return if the PSBT is unchanged after attempted signing(coldcard does this), but it won't know how to diagnose it.

**Comment by jb55** [comment]
I think the thing that tripped be up is that it was prompting me to sign (I had to press the button), and it made it look like it was working properly, but it didn't do anything.

**Comment by instagibbs** [comment]
I see. Maybe the trezor driver could be a bit smarter.

**Comment by achow101** [comment]
#516 added a `signed` field in the response so it is now more obvious if any signing actually happened. The behavior of clicking through signing prompts on the Trezor is due to the way that HWI handles external inputs, which should be revisited at some point.
