### ISSUE TITLE
Error Handling

### ISSUE THREAD

**Issue by nopara73** [bitcoin-core/HWI#207]
Some commands don't have correct error outputs. They don't return `json`, nor they have error code.

# Commands With Incorrect Error Output

`signtx`, `getxpub`, `signmessage`, `getkeypool`, `displayaddress`, `sendpin`

```
hwi signtx
usage: hwi signtx [-h] psbt
hwi signtx: error: the following arguments are required: psbt

hwi getxpub
usage: hwi getxpub [-h] path
hwi getxpub: error: the following arguments are required: path

hwi signmessage
usage: hwi signmessage [-h] message path
hwi signmessage: error: the following arguments are required: message, path

hwi getkeypool
usage: hwi getkeypool [-h] [--keypool] [--internal] [--sh_wpkh] [--wpkh]
                      [--account ACCOUNT] [--path PATH]
                      start end
hwi getkeypool: error: the following arguments are required: start, end

hwi displayaddress
usage: hwi displayaddress [-h] (--desc DESC | --path PATH) [--sh_wpkh]
                          [--wpkh]
hwi displayaddress: error: one of the arguments --desc --path is required

hwi sendpin
usage: hwi sendpin [-h] pin
hwi sendpin: error: the following arguments are required: pin
```

# Commands With Correct Error Output

`getmasterxpub`, `setup`, `wipe`, `restore`, `backup`, `promptpin`

```
hwi getmasterxpub
{"error": "You must specify a device type or fingerprint for all commands except enumerate", "code": -1}

hwi setup
{"error": "You must specify a device type or fingerprint for all commands except enumerate", "code": -1}

hwi wipe
{"error": "You must specify a device type or fingerprint for all commands except enumerate", "code": -1}

hwi restore
{"error": "You must specify a device type or fingerprint for all commands except enumerate", "code": -1}

hwi backup
{"error": "You must specify a device type or fingerprint for all commands except enumerate", "code": -1}

hwi promptpin
{"error": "You must specify a device type or fingerprint for all commands except enumerate", "code": -1}
```

**Comment by achow101** [comment]
What you see here are the result of two different error handlers. The first group have a list of required arguments. The `argparse` argument parser package is checking that the required arguments are there and throws an error if not. This is not something that is handled by HWI but rather by `argparse`. I do not know how to have `argparse` return different error messages.

The second group do not have required arguments, so `argparse` doesn't complain. At that point, it hits HWI's own argument handling which checks that certain optional arguments are provided. At this point, you get the JSON errors as you expect.

**Comment by nopara73** [comment]
https://github.com/bitcoin-core/HWI/issues/180

> Error codes are already in use for every single error. If an error code is missing from any output that's an error, then it's a bug.
