### ISSUE TITLE
`import hwi` crashes REPL

### ISSUE THREAD

**Issue by justinmoon** [bitcoin-core/HWI#213]
```
>>> import hwi
usage:  [-h] [--device-path DEVICE_PATH] [--device-type DEVICE_TYPE]
        [--password PASSWORD] [--stdinpass] [--testnet] [--debug]
        [--fingerprint FINGERPRINT] [--version] [--stdin] [--interactive]
        {enumerate,getmasterxpub,signtx,getxpub,signmessage,getkeypool,displayaddress,setup,wipe,restore,backup,promptpin,sendpin,installudevrules}
        ...
: error: the following arguments are required: command
```

This was my first interaction with the library and was pretty confused for 5 minutes. I'm not familiar enough with the library to guess what the correct behavior is here, but it shouldn't crash the REPL IMO.

**Comment by nopara73** [comment]
Haven't used it that way, but try`import hwi enumerate`.

**Comment by achow101** [comment]
Try `import hwilib`. `import hwi` shouldn't work at all...

**Comment by justinmoon** [comment]
Yea I got it working. I'm just giving feedback that it's a little confusing to attempt `import <library name>` and have the REPL crash.
