### ISSUE TITLE
[Feature] Introduce "--device-model"

### ISSUE THREAD

**Issue by nopara73** [bitcoin-core/HWI#223]
It"d be the same as "device-type" but more specific. Eg. trezor -> trezort + trezorone, leger -> ledgernanos, ledgernanox.

This'd be especially useful in some cases, like trezor setup. With Trezor T I can just tell the device to setup and it does everything by itself, however with Trezor One, I have to fire up a hwi console app, because setup requires a fair bit of interaction.

However I cannot differentiate between them based on what hwi enumerate tells me, so I'll have to ask the user what device he has before giving out the command.

**Comment by achow101** [comment]
I think we could just expand `device-type` to include the specific models while keeping the current generic types that could be multiple models. For example, if you just use `trezor`, it would talk to any Trezor device. But if you specified `trezorone`, then it will only communicate with a Trezor One.

**Comment by nopara73** [comment]
Good idea. In enumerate this won't break software silently, which is good.
