### ISSUE TITLE
"installudevrules" fails in virtual environment

### ISSUE THREAD

**Issue by justinmoon** [bitcoin-core/HWI#234]
From a vanilla Python 3 virtual environment:

```
$ hwi installudevrules
{"error": "installudevrules failed: [Errno 2] No such file or directory: 'udev'", "code": -13}
```

**Comment by nopara73** [comment]
pinging @lontivero

**Comment by lontivero** [comment]
That bug was fixed a month ago. I will be included in the next release by sure.
https://github.com/bitcoin-core/HWI/pull/227

**Comment by achow101** [comment]
@justinmoon Did you install using pip or are you using the prebuilt binaries?

**Comment by achow101** [comment]
Did some testing, and it looks like the issue is because the folder of udev rules is not being included in the archive uploaded to PyPI.

**Comment by justinmoon** [comment]
@achow101 was using pip
