### ISSUE TITLE
BitBox 02 support

### ISSUE THREAD

**Issue by Sjors** [bitcoin-core/HWI#235]
I have a beta BitBox 02 so I can test stuff.

It (obviously?) doesn't work out of the box (haha) with what we have now:

```
./hwi.py enumerate
[]
```

```
./hwi.py -t digitalbitbox -d 0001:0001:00 -p "super strong password" getmasterxpub
{"error": "open failed", "code": -3}
```

cc @jonasschnelli

**Comment by achow101** [comment]
This is currently in the works: https://github.com/achow101/hardware-wallet-interface/tree/bitbox2

The main blocker right now is the lack of signing functionality in the provided python library. See https://github.com/digitalbitbox/bitbox02-firmware/issues/101

**Comment by Sjors** [comment]
I'm not opposed to merging without signing support if that's going to take a while.

Can confirm `enumerate` works as well as `--fingerprint=.... getmasterxpub` (so an easier syntax than version 1). This works without entering the password on the (beta) device by the way.

I was able to import a keypool, but noticed that the (mainnet) address space doesn't match the bech32 address space in the regular app. Maybe the regular app doesn't use BIP 84?

**Comment by x1ddos** [comment]
Curious what the status here is. @Sjors did you get any further?

**Comment by benma** [comment]
I think @TheCharlatan has some integration code somewhere. Not sure what the status is.

**Comment by TheCharlatan** [comment]
I've pushed my work to this branch here: https://github.com/TheCharlatan/HWI/tree/BitBox02 , but integration is pending #307

**Comment by SCBuergel** [comment]
Bump - Any update on this?

**Comment by benma** [comment]
I am picking up the work and I hope to make a PR soon.

@achow101 the BitBox02 has an unlock step which involves confirming a pairing code. The password is entered on the device only. Initially I was gonna (ab)use `promptpin` to initialize the unlock, but saw that this is very specific to the Trezor, e.g. it has a pin GUI dialog and works in combination with `sendpin`.

What would be your preferred solution to this?

a) add a `pair` subcommand
b) use `promptpin` anyway, but show a different dialog in the GUI if it is a BitBox02?
c) a more general `unlock` subcommand?
d) something else?

Also, do you already have a BitBox02?

Thanks for your input.

**Comment by achow101** [comment]
I do have a BitBox02 although I haven't used it  in a while and I don't quite remember the process with using it.

I think it's fine to use `promptpin` anyways. Is the unlocking similar enough to Trezor's PIN entry that we could reuse the same GUI dialog?

**Comment by benma** [comment]
Hi. The unlock is much different: the device password is entered on the device itself (not on the host), after which a pairing code is shown on the device and on the host (the first time only). The user should confirm (or reject) that the code is the same.

There is no PIN code to be entered for the BitBox02 on the host, like there is for the Trezor.

**Comment by benma** [comment]
PR opened to add BitBox02 support https://github.com/bitcoin-core/HWI/pull/363

**Comment by prusnak** [comment]
PR https://github.com/bitcoin-core/HWI/pull/363 merged - so this should be closed?
