### ISSUE TITLE
[Bug] The second inputs address reusing does not seem to be signed correctly

### ISSUE THREAD

**Issue by NicolasDorier** [bitcoin-core/HWI#244]
So I am still unsure of what happened, and need to make sure to check if I can reproduce:

1. I created a PSBT with all the keypath to `(accountKeyFingerPrint, 0/x)`.
2. I ran `signtx` with my ledger nano S.
3. Result was a PSBT where everything was well signed... except 1 input which was not signed.

This input had the strange particularity:
1. All inputs EXCEPT this one had their keypath rewritten to `(masterFingerprint, 49'/0'/3')` (I assume that HWI brute forcing the correct path?)
2. This input was the only one which came from an address which was reused in the same PSBT.

I took the PSBT, and signed a second time, and it completed the missing signature.

I will try to make a repro.

**Comment by instagibbs** [comment]
Which device?

**Comment by NicolasDorier** [comment]
@instagibbs Ledger Nano S.

But trying to replicate I think I am wrong on `I created a PSBT with all the keypath to (accountKeyFingerPrint, 0/x).` ... It MIGHT be a problem on my side... trying to dig around.

**Comment by instagibbs** [comment]
Ok let me know if you reproduce.

**Comment by NicolasDorier** [comment]
I will close this I can't replicate... weird

**Comment by instagibbs** [comment]
This is a reasonable test case to add to CI.

**Comment by NicolasDorier** [comment]
@instagibbs frankly I don't know, this may have come from my code as well. This is very strange because it happened on mainnet, and could not reproduce on my regtest with the exact same steps. (I can't repro on mainnet either because I have no UTXO left now)

**Comment by nopara73** [comment]
> I have no UTXO left now

You can always come to work to Wasabi 😄
