### ISSUE TITLE
coldcard multisig testing coverage

### ISSUE THREAD

**Issue by instagibbs** [bitcoin-core/HWI#248]
we need it

@justinmoon you said there's a bug currently with native segwit outputs? may want to wait until that is fixed.

**Comment by justinmoon** [comment]
@peter-conalgo just released a new ColdCard firmware that he says fixes it. Have not tested yet, but will today.

**Comment by instagibbs** [comment]
@justinmoon I forget, is this confirmed working? Thinking about writing support again here.

**Comment by achow101** [comment]
Multisig on coldcard works so long as the xpubs are registered with the device first. However an important thing to note is that they require BIP 67, so a `sortedmulti` descriptor would need to be used.

Their other methods of registering xpubs requires supporting the PSBT xpub field which we do not yet support.
