### ISSUE TITLE
Trezor T doesn't work anymore on Windows 10

### ISSUE THREAD

**Issue by nopara73** [bitcoin-core/HWI#259]
Tested with multiple Trezor Ts with multiple firmwares and with multiple HWI versions (1.0 and 1.0.2)

Trezor T stopped working a while ago with HWI on Windows 10, other OSs are working, even Windows 7, and also it works with Trezor's website.  

The issue is that `enumerate` doesn't find the device anymore.

https://github.com/zkSNACKs/WalletWasabi/issues/2117

**Comment by achow101** [comment]
Interesting that it had worked previously but no longer does. This could just be that the version of the trezor library has become outdated.

**Comment by nopara73** [comment]
Every other platform works fine (even win7.) We suspect a Windows update broke it for the following reasons.  
Precisely we tested 2 Trezor Ts on 3 Windows 10 computers (2 of which it was working previously.)

I vaguely remember @NicolasDorier complaining on Twitter regarding a Windows update made hardware wallets useless or something like this. Although other hardware wallets are working properly, (even Trezor One) so not sure what was that about. It may be related. Any context on this @NicolasDorier?

**Comment by achow101** [comment]
Are they all using the same firmware version, or different firmware versions? Have the devices been updated since they last worked?

**Comment by MaxHillebrand** [comment]
The user report in zkSNACKs/WalletWasabi#2117 did not update the trezor firmware in between it working / not working. The same trezor worked on Mac + Wasabi without issues.

**Comment by nopara73** [comment]
I tried with the version that it arrived 2.0.x and then update it to the newest 2.1.y. Same was happening.

**Comment by NicolasDorier** [comment]
@nopara73 I complained because an update of Windows 10 is showing a popup every times a packet is sent to U2F device.

**Comment by achow101** [comment]
I've only just now had the opportunity to look at this. It seems that the issue is to do with pyinstaller/our pyinstaller config. Running from source works fine, but running the built exe (both released and master, and 1.0.2 source) does not work.

**Comment by achow101** [comment]
@nopara73 Is the Trezor One that is detected still using hid (the path begins with hid)? Or does it use webusb (path begins with webusb)? I've tested using a Trezor One that uses webusb and it is not detected, so I suspect the issue is with webusb.

**Comment by achow101** [comment]
Ah, I've figured it out. It's related to permissions. It works when you run as Administrator.

**Comment by nopara73** [comment]
Sounds good that you figured out the issue. Trezor Bridge dependency requirement would be clunky. Although there's a 99% chance the user have it installed anyway :/

@prusnak by any chance did you encounter this? If so, do you have any suggestion?

**Comment by prusnak** [comment]
My suggestion is to use whatever Electrum uses.

**Comment by NicolasDorier** [comment]
> Electrum resolved it by preferring the Trezor Bridge interface

Please do not. This require one more thing to deploy and document on the user machine.

**Comment by P0u1us** [comment]
FYI: the issue is not only with Trezor but with KeepKey as well:
See; https://www.reddit.com/r/keepkey/comments/ddn7rn/keepkey_issue_with_electrum/

**Comment by nopara73** [comment]
This issue is about Trezor T. Trezor One works properly and KeepKey is a clone of Trezor One, so I suspect it's an entirely different issue.

Is anyone able to test KeepKey with HWI on win10? (I'm asking it out of curiosity, we're not officially supporting it in Wasabi.)

**Comment by achow101** [comment]
I tested with a KeepKey, it does not work either. Nor does my Trezor One. Both the KeepKey and Trezor One have been updated to versions which use the WebUSB interface rather than the HID interface. The Trezor T also uses WebUSB. I believe this issue is caused by the WebUSB interface and is not specific to just the Trezor T.

**Comment by NicolasDorier** [comment]
@achow101 I know that Windows did some fuckery with WebUSB, @btchip complained about it to me a while ago. Maybe he can give more details as to what exactly changed.

**Comment by btchip** [comment]
Yeah, 2 different issues here I think.

Issue 1 : Accessing a device declaring a U2F interface is tricky under 1903. It should work if running the process as an Administrator. The long term solution seems to be to migrate to a different libusb version (including https://github.com/libusb/libusb/pull/603)

Issue 2 : migration to a WinUSB interface. You'll have to use a different library to communication to the device (old memories, but PyUSB should do the job in Python - see https://github.com/LedgerHQ/btchip-python/blob/v0.1.14/btchip/btchipComm.py which supported both interfaces back in the days)

**Comment by achow101** [comment]
> Issue 1 : Accessing a device declaring a U2F interface is tricky under 1903. It should work if running the process as an Administrator. The long term solution seems to be to migrate to a different libusb version (including [libusb/libusb#603](https://github.com/libusb/libusb/pull/603))

It looks like libusb 1.0.23 has this fix, and I just checked that using 1.0.23 does work on Windows 10. However, libusb doesn't provide precompiled binaries of that version, so we will need to compile it ourselves during the build.

**Comment by nopara73** [comment]
Can you roll out a release so I can push it through my HWI test suite?
