### ISSUE TITLE
[feature] A gui interface

### ISSUE THREAD

**Issue by achow101** [bitcoin-core/HWI#263]
In light of https://github.com/bitcoin/bitcoin/pull/16944, it would probably be useful to have a GUI interface that people can use.

**Comment by Sjors** [comment]
Could lift stuff from https://github.com/justinmoon/junction or https://github.com/cryptoadvance/specter-desktop

To keep it simple, maybe we should limit functionality to:
1. Single device
2. Creating a watch-only wallet
3. Signing a PSBT that user can copy-paste from Core
4. Broadcasting the resulting signed PSBT via RPC

This avoids having to implement a full fledged send screen. 

Meanwhile a WIP with the reverse approach (having Bitcoin Core GUI use HWI) is here: https://github.com/bitcoin/bitcoin/pull/16549

**Comment by achow101** [comment]
My idea is that it would just directly mirror the CLI API rather than trying to implement a complete wallet software.

So really, there will be a radiobutton group with the list of devices so the user can choose which device to use, then a box for a PSBT to sign a transaction, and then just some buttons to trigger getkeypool, displayaddress, etc.

**Comment by instagibbs** [comment]
> My idea is that it would just directly mirror the CLI API rather than trying to implement a complete wallet software.

Agreed for first draft. But...

95% of the headache of making these wallets now is the importing of records, and not importing to an already-existing wallet

1) User downloads Core syncs
2) User install HWI-GUI
3) User starts up HWI-GUI, configures RPC connection to Core
4) User does a Create wallet wizard:
  a) Chooses name. no duplicates via `listwallets` lookup
  b) Chooses what type of device they will have plugged in(or autodetects, whatever)
  c) Click "create", it does `getkeypool` to specified hww, `createwallet` to Core RPC, `importmulti` to that wallet endpoint
5) User can go back to using Core wallet like normal, copying/pasting details as needed
6) Profit

I think the same could be done with displayaddress, which is the other PITA part right now.
4) paste in address to HWI-GUI for display
5) calls `getaddressinfo` -> `displayaddress <address descriptor>`

**Comment by justinmoon** [comment]
@pierre_rochard and I are taking a hack at this today.

**Comment by achow101** [comment]
I think another thing that would be useful is a GUI which does interactive GUI things as part of the integration into other software. The currently proposed and implemented GUI stuff are largely stop-gap measures while we work on integrating HWI into Core. But I think it would be useful to also have the GUI be something that software can call to do things that aren't otherwise possible with the command line or require some form of interaction to be smooth. Basically things that integrators would have to make their own GUIs for.

For example, for PIN entry for Trezor and Keepkey, we could have something like `hwi-qt.py pinentry` which would then show the dialog for that and do the whole `promptpin` then `sendpin` thing without bitcoin-qt having to implement that itself (a dialog for users to enter the PIN and all that). Same for passphrases. We could also have a dialog box to show the enumerated devices and let users select the device to use. Then we would return the JSON object with the options that are needed for that device. We could even make HWI take the JSON object directly as an alternative to specifying each option individually in the command line args.

Thoughts on doing something like this? I think this would make integrating into GUI applications much easier as implementors wouldn't need to create their own UIs, but having to support both `hwi` and `hwi-qt` in Core would make it more difficult to maintain as they would be kind of divergent.
