### ISSUE TITLE
ColdCard & Testnet

### ISSUE THREAD

**Issue by justinmoon** [bitcoin-core/HWI#268]
ColdCard has an option in `Settings > Blockchain` to choose between "Bitcoin" and "Testnet: BTC".

If you have "Bitcoin" selected, you can instantiate a `hwi.devices.coldcard.ColdcardClient` with `client.is_testnet = True` and all methods will do mainnet operations. For example, call `client.get_pubkey_at_path` and you will get an xpub -- not a tpub.

**Comment by peter-conalgo** [comment]
The current Coldcard protocol doesn't have a way to check the mode of the Coldcard w.r.t mainnet versus testnet. I see that gets added. Then HWI can test that if needed.

**Comment by peter-conalgo** [comment]
[ckcc-protocol](https://pypi.org/project/ckcc-protocol/) has been updated to version 0.8.0 which includes a new command: `chain` (on CLI) and `block_chain()` in python.
- requires version 3.0.1 of Coldcard firmware (which is obscure at this point)
- returns string "BTC" or "XTN"

**Comment by nopara73** [comment]
I'd also prefer if coldcard wouldn't be aware of the network, too, or rather the softwar would tell coldcard about the network and not the user has to manually configure it, just like it was previously.

**Comment by KayBeSee** [comment]
I also believe the `getmasterxpub` command is returning the wrong value for coldcard.

It is returning the xpub at `m/44'/0'/0'` but it really should return the xpub from just `m`. When I generate an xpub using the `getmasterxpub` command, the device fingerprint is incorrect but when I get the xpub using `getxpub "m"` I get an xpub that generates the correct fingerprint for my device.

**Comment by ceyonur** [comment]
@KayBeSee seems like it is not limited by coldcard. masterxpub always return `m/44'/0'/0'`(bip44). I believe its becoming a problem and also a little bit confusing. another related issue is #309 . Moreover I noticed that some of the new hsm coldcard features conflict with this bip44 masterxpub approach. @achow101 tells that not all devices support exporting pure master `m` xpub. Can it be at least dynamic to device type? so we can at least support some devices for a true getmasterxpub?
