### ISSUE TITLE
`hwi enumerate` taking 20 seconds on Windows

### ISSUE THREAD

**Issue by justinmoon** [bitcoin-core/HWI#269]
Every once in a while `hwi enumerate` will take 20 seconds on my Windows 10 machine.

In such cases, [this timeout](https://github.com/bitcoin-core/HWI/blob/master/hwilib/devices/trezorlib/transport/udp.py#L88) gets hit for both trezor and keepkey, adding up to 20 second duration.

@nopara73 @lontivero Do you guys ever see this?

Thoughts on lowering the timeout? (cc @prusnak)

**Comment by prusnak** [comment]
It makes sense to lower the timeout to 1 second here: https://github.com/bitcoin-core/HWI/blob/master/hwilib/devices/trezorlib/transport/udp.py#L88

Another option is to not use UDP transport at all as this is needed only for the emulator. And the inclusion of the UDP transport could be hidden behind a command-line option for example.

**Comment by ormick8** [comment]
I'm the real G.O.A.T
