### ISSUE TITLE
Could not open client or get fingerprint information

### ISSUE THREAD

**Issue by sean208208** [bitcoin-core/HWI#271]
I buy the ledger always tell me the finger printer is wrong while using HWI

python3 ./hwi.py enumerate
[{"type": "ledger", "model": "ledger_nano_s", "path": "0003:001b:00", "error": "Could not open client or get fingerprint information: open failed", "code": -13}]

Is there any way to solve it?

**Comment by sean208208** [comment]
> Did you open the Bitcoin app on your ledger first?

Yes, I open already

**Comment by instagibbs** [comment]
can you list releases you're running, HWI, Ledger firmware, etc.

**Comment by sean208208** [comment]
> can you list releases you're running, HWI, Ledger firmware, etc.

ubuntu 16.04
python 3.7.2
ledger nano s

sudo apt install libusb-1.0-0-dev libudev-dev

pip3 install hidapi # HID API needed in general
pip3 install ecdsa
pip3 install pyaes
pip3 install typing_extensions
pip3 install mnemonic
pip3 install libusb1

git clone https://github.com/bitcoin-core/HWI.git
cd HWI

./hwi.py enumerate

I am outside now, can't give the screenshot

**Comment by instagibbs** [comment]
manually checked on HWI master, my Nano X gives fingerprint properly(since CI doesn't test ledger)

**Comment by sean208208** [comment]
> manually checked on HWI master, my Nano X gives fingerprint properly(since CI doesn't test ledger)

Can you tell me what releases you use, I well check on Monday

So I don't need to use Ledger Live app, just connect ubuntu and use HWI is correct?

Thanks

**Comment by sean208208** [comment]
I install Bitcoin app and create one account on ledger nano s already

**Comment by achow101** [comment]
Did you install the [udev rules](https://github.com/bitcoin-core/HWI/tree/master/hwilib/udev)?

**Comment by sean208208** [comment]
> Did you install the [udev rules](https://github.com/bitcoin-core/HWI/tree/master/hwilib/udev)?
> 
> `open failed` error means that HWI was unable to actually connect to the device, usually due to udev rules, or something else is connected to the device.

I just install 51-android.rules, I will try on Monday

Thanks

**Comment by sean208208** [comment]
Thanks  @achow101,  my problem is solves.
