### ISSUE TITLE
[Feature] Support SLIP-132 ypub/zpub/Ypub/Zpub extraction

### ISSUE THREAD

**Issue by kdmukai** [bitcoin-core/HWI#281]
## The problem
Currently `get_pubkey_at_path` always returns "xpub" prefixed pubkeys for mainnet or "tpub" for testnet, regardless of derivation path.

However, wallets like Electrum follow [SLIP-132](https://github.com/satoshilabs/slips/blob/master/slip-0132.md) which defines version bytes applied to newer derivation paths in order to generate pubkeys prefixed with ypub/zpub/Ypub/Zpub for mainnet and upub/vpub/Upub/Vpub for testnet.

It would be convenient (and a lot less confusing) if HWI at least had an option to output the same pubkeys that appear elsewhere.

## Suggested changes, early implementation
I've begun implementing a version of `get_pubkey_at_path` that includes an `as_slip132` option that would apply the corresponding SLIP-132 version bytes to any recognized derivation path.

See my ledger implementation [here](https://github.com/kdmukai/HWI/blob/slip-132/hwilib/devices/ledger.py#L85)
And the version bytes mapping defined [here](https://github.com/kdmukai/HWI/blob/slip-132/hwilib/hwwclient.py#L5)

My work-in-progress version also adds a `force_prefix` optional arg that could specify a prefix like "Zpub" that doesn't have an explicit derivation path mapping in SLIP-132 (presumably because multisig derivation paths weren't standardized?). This way a derivation path like Electrum's `m/48h/0h/0h/2h` (which is not mapped in SLIP-132) can still yield the exact same Zpub from HWI that Electrum itself pulls from the same hardware wallet.

## Rationale
This `as_slip132` option fully preserves HWI's existing functionality and leaves the current xpub output as-is to avoid any reverse-compatibility issues/expectations. But if a user wants the SLIP-132 pubkeys, s/he could now explicitly ask for them.

The `force_prefix` option is kind of a regrettable compromise to handle the not-standardized multisig derivation paths and yet still be able to yield the somewhat(?) standard Zpub/Ypub pubkeys.

## Seeking feedback
I'm happy to finish this implementation (implement for all devices, update CLI, add tests) and generate a PR but I'd like to see if there's support for this before I put in any further work.

* Is SLIP-132 support in HWI good/bad/unthinkable?
* Is the `as_slip132` option necessary or should `get_pubkey_at_path` just return SLIP-132 pubkeys going forward?
* etc...

**Comment by achow101** [comment]
Concept NACK

I really dislike the whole ypub/zpub stuff. It's really such a hack. It doesn't generalize well and overloads something that does not and should not care about script types at all. I think that software developers should instead move to using output descriptors (and Electrum is doing that) which are way more flexible and human readable than ypub/zpub. IMO HWI should not implement these, especially in a get xpub command where the script types does not and should not matter at all.

**Comment by instagibbs** [comment]
I tend to concept NACK as well for the same reasons.

Aside: I wonder if there's a tool out there to convert x/y/zpub format to descriptor. That could be helpful to point people to.

**Comment by nopara73** [comment]
NACK. When we considered it in Wasabi, we looked into other wallets and turned out all of them are using them in a different, incompatible, non-slip following way. There's a huge rabbit hole here.
