### ISSUE TITLE
How to prompt for passphrase on Trezor T

### ISSUE THREAD

**Issue by NicolasDorier** [bitcoin-core/HWI#283]
Trezor T users seems to enter the pin before the device it can get enumerated.

However, I would like them to enter the passphrase after I can enumerate it. How do I prompt them to enter the password on the device?

**Comment by achow101** [comment]
Doing a `getxpub` (or `getmasterxpub`) will prompt the Trezor T to ask for the passphrase.

**Comment by NicolasDorier** [comment]
thanks a lot!

**Comment by stevenroose** [comment]
This seems to be broken in 2.0.0. I think it might be a firmware issue as well.

**Comment by prusnak** [comment]
@stevenroose Are you on the latest firmware? If not, update and try again. If yes, please report the version number.

**Comment by NicolasDorier** [comment]
There was something probably broken in trezor, but I don't think that's related to hwi 2.0

https://github.com/btcpayserver/BTCPayServer.Vault/issues/29

**Comment by prusnak** [comment]
> This seems to be broken in 2.0.0. I think it might be a firmware issue as well.

Fix probably in https://github.com/bitcoin-core/HWI/pull/495

**Comment by stevenroose** [comment]
Yeah I can confirm that #495 fixes this.
