### ISSUE TITLE
Trezor T: How to know that the user want to enter passphrase on host?

### ISSUE THREAD

**Issue by NicolasDorier** [bitcoin-core/HWI#286]
There is no difference in the way Trezor T behave if the user click "enter passphrase on device" or "enter passphrase on host" when prompt by the device.

So software side, how can I know if I should ask the users to write the passphrase on the host?

**Comment by achow101** [comment]
Passphrase on host means that the `--password` option is set. You shouldn't need to prompt for passphrase on host.

I'm not sure that we should allow passphrase on host for the Trezor T.

**Comment by NicolasDorier** [comment]
> I'm not sure that we should allow passphrase on host for the Trezor T.

I know, but that's not my problem.
My problem is that here is what happen to the user:

* I detect that Trezor T need passphrase
* I show on the UI to the user "please enter the passphrase on the device"
* The user see "do you want to enter the passphrase on device, or on host?"

Now if the user enter the passphrase on device => No problem, the call to getxpub finish, next commands are using the passphrase that the user set on the device.

If the users select "enter the passphrase on the host" => Problem, because the call to getxpub finish as well exactly as if the user entered the passphrase on the device. So I don't know if I must show or not the form on the host to enter the passphrase.

**Comment by achow101** [comment]
In that case, we can disallow passphrase on host and it'll throw an error.
