### ISSUE TITLE
Issues running `run_tests.py --all`

### ISSUE THREAD

**Issue by instagibbs** [bitcoin-core/HWI#288]
Trezor: 
`trezor_1: test_enumerate (test_device.TestDeviceConnect) ... /bin/sh: 1: ./trezor.elf: not found` and exits

Trezor T:
`trezor_t: test_enumerate (test_device.TestDeviceConnect) ...` and hangs

Coldcard works, but when it exits it often leaves `/tmp/ckcc-simulator.sock` lying around which confuses other tests during `enumerate`.

**Comment by achow101** [comment]
Is this still an issue? Some cleanup things have been added to the test since this was opened.

I haven't been able to replicate any hangs with trezors.

**Comment by instagibbs** [comment]
Don't have the time to test again this week sorry
