### ISSUE TITLE
Unable to enumerate monero based apps

### ISSUE THREAD

**Issue by Kryptoxic** [bitcoin-core/HWI#296]
Recently, I updated my copy of the repo with the latest code and attempted to retrieve the address from my monero app as a test and I keep receiving the following message.

![image](https://user-images.githubusercontent.com/15937274/71793690-dcfd0680-3078-11ea-8c9d-b05a9edeb6f0.png)

I have confirmed that the app is working normally using the monero gui and cli wallet. This happens with other apps that are based on monero as well.

**Comment by achow101** [comment]
Monero is not supported by this project.

**Comment by Kryptoxic** [comment]
If it is not supported, why was I able to use it with previous version of the monero app and monero based apps?

**Comment by achow101** [comment]
> If it is not supported, why was I able to use it with previous version of the monero app and monero based apps?

I don't know. HWI was not and is not tested with nor designed for anything other than the Bitcoin app. Any other app working with it is a coincidence and you should not rely on it working for anything else.
