### ISSUE TITLE
Weird Namespace stdout loggging

### ISSUE THREAD

**Issue by KayBeSee** [bitcoin-core/HWI#310]
I am writing a Javascript wrapper around this library but for the `getxpub` command I am getting some weird, non-JSON back before the JSON response. Is there an argument I need to pass in to prevent getting the `Namespace(command=....)` from stdout before the JSON object with the xpub? I looked through the code and don't see where this output is coming from.

```
$ ./hwi.py -t coldcard -d "IOService:/AppleACPIPlatformExpert/..." getxpub "44'/0'/1'/0/0"
Namespace(command='getxpub', debug=True, device_path='IOService:/AppleACPIPlatformExpert/PCI0@0/yadayadayada', device_type='coldcard', expert=False, fingerprint=None, func=<function getxpub_handler at 0x1080cfb90>, interactive=False, password='', path="44'/0'/1'/0/0", stdin=False, stdinpass=False, testnet=False)
{"xpub": "xpub6Gkkf2C2KHrJFM7Tx4jtyABqfveWb9iGDhM91vocMEE2ovfrqPimu4AUnJnt4ptHEYTPGoaK8S45jgPyWgbnWJK8UTEWp8bhcF5WecdFpnH"}
```

**Comment by achow101** [comment]
That looks like `args` in `hwilib/cli.py` is getting printed out (i.e. there's a `print(args)` somewhere in there, but I don't see where that might occur. I've not seen this issue before, are you sure that you don't have a local modification that adds that print?

**Comment by KayBeSee** [comment]
Ahh, yes that's it! I must have added it when I was initially messing around with the library.
