### ISSUE TITLE
hwi 1.1.0 installation fails on arm

### ISSUE THREAD

**Issue by k9ert** [bitcoin-core/HWI#331]
As i discovered on https://github.com/rootzoll/raspiblitz/issues/1171 one of the dependencies, the pyside2 package, is not available on arm:
https://pypi.org/project/PySide2/#files

As HWI is pretty useful in a command-line-only environment, imho the pyside2 dependency should somehow be marked optional. It seems that https://www.python.org/dev/peps/pep-0508/#extras has a recommendation on how to do that. 

Is that the way to handle it? I might create a PR if someone can confirm?!

**Comment by achow101** [comment]
yes, the gui should be marked optional. This should be done in `pyproject.toml`.

**Comment by achow101** [comment]
@k9ert Can you test #332?

**Comment by k9ert** [comment]
> @k9ert Can you test #332?

Done. Thank you very much for the fast response!

**Comment by k9ert** [comment]
#322 is now closed. How often do you create new releases? Can i help with that somehow?

**Comment by achow101** [comment]
@k9ert Can you test [1.1.1-rc.1](https://github.com/bitcoin-core/HWI/releases/tag/1.1.1-rc.1) just to make sure that other build changes didn't affect this?

**Comment by k9ert** [comment]
Yes, i will but won't be able until 03-04.June.

**Comment by k9ert** [comment]
I've tested the new release and it works. Thanks for letting me know about the RC nevertheless.
