### ISSUE TITLE
Mac Build Failure

### ISSUE THREAD

**Issue by achow101** [bitcoin-core/HWI#335]
Travis is currently failing to build the Mac binaries: https://travis-ci.org/github/bitcoin-core/HWI/jobs/690750926 which is a problem as we use Travis to build the Mac binaries for release.

Unfortunately I don't have a Mac to debug this. Can someone with a Mac take a look at that and try to figure out what's wrong? Alternatively, I should get a Mac (or someone can buy me one).

**Comment by instagibbs** [comment]
what are the specific steps to reproduce? I might be able to take a look.

**Comment by achow101** [comment]
Looks like it's just with running `contrib/build_bin.sh`. You might want to install pyenv first though. It's all in `travis.yml`.

**Comment by instagibbs** [comment]
Looks like my build on OSX 10.15.4 works fine :/
