### ISSUE TITLE
Trezor T tests failing

### ISSUE THREAD

**Issue by achow101** [bitcoin-core/HWI#337]
The current master branch for the Trezor T fails the tests. This is probably due to a recent change which disallows non-standard HD keypaths.

**Comment by tsusanka** [comment]
Looking very briefly into this it seems to me you are using Testnet paths in the tests:

https://github.com/bitcoin-core/HWI/blob/master/test/test_device.py#L466

For this to work on Trezor T we now also require the `coin_name` to be set correctly, in this case to "Testnet". You can either use a Bitcoin path (44'/0'/0'/0/0 for example) or provide the coin_name attribute.

Example using trezorctl:
```
trezorctl get-address -dn "44'/1'/0'/0/0" -c "Testnet"  # no error
trezorctl get-address -dn "44'/1'/0'/0/0"  # error - path does not match the coin (Bitcoin by default)
trezorctl get-address -dn "44'/0'/0'/0/0"  # no error - coin_name is Bitcoin by default
```

I am not sure if this requiers some other changes in HWI to support Testnet with Trezor T.

**Comment by achow101** [comment]
Do the path checks also check address type? e.g. `SPENDWITNESS` is `84'`? If so, does this also apply to multisigs?

I seem to be having an issue with getting the multisig signing test to work, still getting `Forbidden key path` on that.

**Comment by tsusanka** [comment]
We are checking address types whether they match `SPEND[something]` but those are soft-checks (user can confirm and go ahead) and I do not think `Forbidden key path` should be raised.

[These](https://github.com/trezor/trezor-firmware/blob/445f56d387471d6d6c99fa01c8d5e22b6a21868e/core/src/apps/bitcoin/keychain.py#L22) are the paths that are allowed for Bitcoin signing. `coin` should be Bitcoin by default so `84'` should be allowed.

Could you point me to the particular test that is failing? Maybe I'll read something out of it

**Comment by achow101** [comment]
The failure seems to be happening because we are setting the `address_n` to the empty list (`[]`) when [constructing the `MultisigRedeemScriptType`](https://github.com/bitcoin-core/HWI/blob/master/hwilib/devices/trezor.py#L43). I added some extra debugging lines to a local build of the emulator and the specific path it didn't like was `[]` which only occurs in this multisig.

[Here](https://travis-ci.com/github/achow101/hardware-wallet-interface/jobs/343861646) is a travis run that is failing with that error.

**Comment by tsusanka** [comment]
Yes, `[]` is now disallowed. The Bitcoin app is allowed to manipulate only with keys in the {44', 45', 48', 49', 84'}/0' subtree, again see [here](https://github.com/trezor/trezor-firmware/blob/445f56d387471d6d6c99fa01c8d5e22b6a21868e/core/src/apps/bitcoin/keychain.py#L22).

So changing that to `44'/0'/0'` for example should fix the problem. Is that something you could do?

**Comment by achow101** [comment]
It was my understanding that the pubkeys in `MultisigRedeemScriptType` would be derived from with the given `address_n` as we are providing an xpub (`HDNodeType`) and derivation path (`address_n`). If that is what happens, then `[]` is the correct derivation path and we don't necessarily have the xpubs and derivation paths for the other keys in the multisig.

**Comment by achow101** [comment]
I tried setting that to `m/44h/0h/0h` and the result is a non-specific `'FirmwareError: Firmware error'`

**Comment by tsusanka** [comment]
Yes, you are correct. Apologies, I did not realize. It seems to me the problem might be how you are constructing the `hd_node`. In this [test case](https://github.com/trezor/trezor-firmware/blob/29db76918513cbe828238918a7621a39c065211a/tests/device_tests/test_multisig.py#L44) we are getting the public node using the path `48'/0'/i`.

Let me cc @matejcik here, he is more skilled in that area and might help more effectively.

**Comment by tsusanka** [comment]
I do not know what seed you are using in the tests, but this hd_node should work IMHO on the `12 * all` seed:

```
HDNodeType:
 	{
 		'depth': 3
 		'fingerprint': 4256967275
 		'child_num': 2147483649
 		'chain_code': b'\xc1\x9c\xab=\xd0\x1e\xd5\x86\xf8\xa8\\\xd4\x90\xa7M\xe4:\xe1NA\xff\xaf\xa9g\x8c\x9b\x1f\xcac\x00"\xfe',
 		'public_key': b'\x03\x86\xa4\xed\xf1\x05y:V|\x1ba\xff\xb8\xaa\xb72\xcf>\xa1\xb1a\x8f\x1ez\xc3\x8c\x7fI\x13\xdb\x84\x8e'
 	}
``

**Comment by achow101** [comment]
I figured it out. The failure was not because of the multisig having `[]` as the path but rather because one of the places where the signature was getting ignored was not setting `txinputtype.address_n`.
