### ISSUE TITLE
How to package to use in production

### ISSUE THREAD

**Issue by KayBeSee** [bitcoin-core/HWI#341]
Hey Andrew --

I've been using HWI to develop an application but as I go to build it for production, I am noticing that the functionality breaks. I think it has to do with me not building correctly or my builds not including all of the required dependencies.

For example, when using `enumerate` I get devices back when in development mode but when I package and build for production I get back an empty array which makes me think I am hitting this area of code: https://github.com/bitcoin-core/HWI/blob/master/hwilib/commands.py#L47

So how would I go about building HWI with all of its dependencies and then dropping it into my project? Thanks dude, this library is awesome!!

**Comment by KayBeSee** [comment]
Just to follow up, I put some print statements around the enumerate function and it looks like the dependencies are not getting installed when building. I'm a noob when it comes to python but I feel like there should be a way to package everything with the dependencies and then drop into another project (in my case, a node.js project)

**Comment by achow101** [comment]
Releases have prebuilt standalone binaries that you can use: https://github.com/bitcoin-core/HWI/releases

**Comment by KayBeSee** [comment]
Excellent! Those worked perfectly. Thank you!
