### ISSUE TITLE
ECDSA 0.15

### ISSUE THREAD

**Issue by FrancisPouliot** [bitcoin-core/HWI#350]
https://github.com/bitcoin-core/HWI/blob/4c08a59fbdaded356b75e21dddc3bf40acf28cc6/setup.py#L101

I got this error while installing software that depends on HWI

`hwi 1.1.2 has requirement ecdsa<0.14.0,>=0.13.0, but you'll have ecdsa 0.15 which is incompatible.`

Just curious if this is intended

**Comment by achow101** [comment]
What software are you trying to install? It's likely that that software depends on ecdsa 0.15 whilst HWI is currently locked to 0.13.x. There's no particular reason to keep ecdsa at 0.13, it just happened to be what was out when it was added.

**Comment by FrancisPouliot** [comment]
I was installing specter-desktop 

I downgraded to 0.14.1 and it worked.
