### ISSUE TITLE
Please write a protocol

### ISSUE THREAD

**Issue by fresheneesz** [bitcoin-core/HWI#364]
This looks like  a very worthy project, however I don't see any clear way for anyone to use it if they don't want to use python. I also don't see any kind of language-agnostic description of how this works. I would propose that a formalized protocol is written that this library implements, so that both makers of hardware wallets and (especially) software wallets can more easily implement it.

**Comment by achow101** [comment]
Does the [docs site](https://hwi.readthedocs.io/en/latest/) resolve this?

**Comment by fresheneesz** [comment]
I think partially. TBH I don't quite remember where my head was at when I made that comment. It would be very interesting to create a standard protocol that hardware wallets themselves implement, but that clearly isn't quite what this project is about. Then again, it could be an interesting idea to create such a protocol based on the API of this project. In any case, I think you can ignore my comment.
