### ISSUE TITLE
dependency discrepancy for mnemonic

### ISSUE THREAD

**Issue by ZeroPointEnergy** [bitcoin-core/HWI#375]
I'm in the process of packaging this software and stumbled over a discrepancy with the dependencies:

https://github.com/bitcoin-core/HWI/blob/8751d1c725a293c6b94fbe1781656ec3db99604a/setup.py#L104
https://github.com/bitcoin-core/HWI/blob/8751d1c725a293c6b94fbe1781656ec3db99604a/pyproject.toml#L23

Is there really a hard dependency on mnemonic 0.18 (which is quite an old release) or should a newer version work as well?

**Comment by achow101** [comment]
No, there's no hard dependency, I just haven't bothered to update them in a while. I'll update all the deps before the next release.

**Comment by ZeroPointEnergy** [comment]
:+1:  Thanks!
