### ISSUE TITLE
Timeout signing with Coldcard on Windows

### ISSUE THREAD

**Issue by craigraw** [bitcoin-core/HWI#381]
While doing cross platform testing I've noticed that on Windows HWI (1.1.2) seems to have a timeout when signing a transaction, specifically on the Windows (10) platform.

Using hwi.exe, the PSBT is transmitted successfully and the Coldcard (mk2, latest firmware) shows the normal signing screen to check the address etc. After about 10 seconds (and the "Waiting for OK on Coldcard" message, the hwi command returns one of a variety of different error codes, including:

{"error": "not all arguments converted during string formatting", "code": -13}  (this most often)
{"error": "Remote Error: Confused usb.py:304", "code": -7}

The Coldcard continues to show the signing confirmation screen. This happens on two different machines (native and virtualized) so I don't think it's specific to my hardware.

It's worth noting that if you confirm the transaction sufficiently quickly on the Coldcard, HWI correctly returns the signed PSBT.

**Comment by achow101** [comment]
Can you repeat this but add `--debug` (needs to go after `hwi.exe` and before `signtx`) to your command so we can get some debugging output?

**Comment by achow101** [comment]
Can you post a PSBT that you had this issue with? I am unable to reproduce on my Windows machine.

**Comment by craigraw** [comment]
I figured out the cause - I had a background thread calling enumerate which apparently caused some HWI confusion on Windows.

Apologies for the false alarm.
