### ISSUE TITLE
Q: Are EPS and HWI compatible on the same bitcoin-core node?

### ISSUE THREAD

**Issue by brianddk** [bitcoin-core/HWI#389]
Both [EPS](https://github.com/chris-belcher/electrum-personal-server) and [HWI](https://github.com/bitcoin-core/HWI) seem to import `xpubs` into core using the wallet RPC commands.  If I'm using a HW wallet I'd be importing the same keys into bitcoin-core with both add-ons.  I assume this would result in one of four scenarios: 

1. Core would complain about two wallets watching the same xpubs causing the import to fail
2. Core would happily allow two watch wallets to watch the same addresses, but double the "watch balance"
3. Core would allow the same addresses, and would filter so that the watch balance wasn't doubled
4. EPS and HWI could both name the exact same RPC wallet without issue

Is there a 5th scenario?  Is item 4 viable?

Thoughts?

Reference:
* [xpost of this to EPS issue list](https://github.com/chris-belcher/electrum-personal-server/issues/218)

**Comment by achow101** [comment]
HWI does not interact with Bitcoin Core directly. It does not connect to the RPC and does not create a wallet nor import anything into a wallet. All of that is done either by the user or other software that uses HWI.

***

When you use two different wallets, then everything is treated independently. The things contained within one wallet has no effect on any other wallet loaded. So you can have multiple wallets that watch the same things. So scenario 1 does not occur.

Balances are reported on a per-wallet basis. There is no "all loaded wallets" balance so scenario 2 does not occur.

When you attempt to import the same thing into the same wallet, then nothing will change. You'll probably get some warnings like "script already exists" but those can generally be ignored. Importing the same thing multiple times does not duplicate anything or change the balance.

**Comment by chris-belcher** [comment]
I also strongly suspect that HWI and EPS are compatible. The EPS config file has an option to choose the name of the Core wallet to use, and the setup instructions tell people to create a brand new empty Core wallet.
