### ISSUE TITLE
Errors using displayaddress with multisig output descriptors on Trezor and Coldcard

### ISSUE THREAD

**Issue by craigraw** [bitcoin-core/HWI#392]
I am seeing at least two issues when using displayaddress on multisig wallets with the --desc option. The following testing was done on a 2 of 2 multisig (one Coldcard, one Trezor) using the default derivation paths and /0/0 path suffixes. 

On the Trezor, only P2SH testnet, P2WSH testnet and P2SH mainnet works (although with the latter the Trezor complains of a "wrong address path"). The remainder proceed with no errors, but an incorrect address is displayed on the Trezor. It's unclear where this address comes from. The command used looks similar to:

```
./hwi.py --device-type="trezor" --device-path="webusb:xxx" --testnet displayaddress --desc="sh(wsh(sortedmulti(2,[0f056943/48'/1'/0'/1']tpubDF2rnouQaaYrUEy2JM1YD3RFzew4onawGM4X2Re67gguTf5CbHonBRiFGe3Xjz7DK88dxBFGf2i7K1hef3PM4cFKyUjcbJXddaY9F5tJBoP/0/0,[6ba6cfd0/48'/1'/0'/1']tpubDFcrvj5n7gyatVbr8dHCUfHT4CGvL8hREBjtxc4ge7HZgqNuPhFimPRtVg6fRRwfXiQthV9EBjNbwbpgV2VoQeL1ZNXoAWXxP2L9vMtRjax/0/0)))"
```

Coldcard simply fails with a -13 error. This seems to be because the display_address method at https://github.com/bitcoin-core/HWI/blob/e93dc5cece6dc3aeb7ed059252e30f9702209677/hwilib/devices/coldcard.py#L234 does not use the descriptor parameter, instead using the commands.py derived redeem_script which for a 2 of 2 is '5252ae'. This in turn fails the assertion at https://github.com/bitcoin-core/HWI/blob/e93dc5cece6dc3aeb7ed059252e30f9702209677/hwilib/devices/ckcc/protocol.py#L151

Please let me know if I'm using this functionality incorrectly. FWIW I did try on Specter Desktop 0.8.1 as well, but got the error "Multisig descriptor must include all pubkeys".

**Comment by achow101** [comment]
`displayaddress` is currently confusing to use and implemented confusingly. It's going to be completely overhauled soon.

**Comment by craigraw** [comment]
Thanks for the feedback. Looking forward to incorporating this in a future release.

**Comment by prusnak** [comment]
> On the Trezor, only P2SH testnet, P2WSH testnet and P2SH mainnet works

For Trezor you need to respect the key separation - that is to use the correct coin_type in the bip48 path (`m/48'/0'` for Bitcoin and `m/48'/1'` for Bitcoin Testnet).

**Comment by craigraw** [comment]
Happy to say the situation has much improved with v2. I've successfully tested displaying multisig addresses on Trezor One, Coldcard and Bitbox02 on P2SH-P2WSH and P2WSH, and P2SH on Trezor and Coldcard (Bitbox02 does not support P2SH multisig). Tests were also successful with testnet addresses.

Here are my notes for the `--desc` parameter:
- Output descriptors should use xpubs with key origin and child derivation paths, and not the derived public keys directly
- xpubs in the descriptor must be sorted according to BIP67 for the derived public keys on the address level
- Output descriptors should use `multi` rather than `sortedmulti`

**Comment by instagibbs** [comment]
is this fixed to your satisfaction?

> Here are my notes for the --desc parameter:

When you say "should, are you simply being descriptive? You aren't allowed to do things like `sortedmulti`?

User notes somewhere may be helpful.

**Comment by craigraw** [comment]
> is this fixed to your satisfaction?

Yes - happy to close this off if there are no further comments

> You aren't allowed to do things like `sortedmulti`?

My experience was that:
- Bitbox02 handled it fine
- Trezor often displayed an incorrect address (probably depending on whether the order happened to be incorrect)
- Coldcard failed every time with 'BIP67 violation'

**Comment by instagibbs** [comment]
Ok please open new issues so we can tackle those one by one? 👍
