### ISSUE TITLE
[Q] In arbitrary script signing, how is it determined where to put the sig in the final scriptSig or witness?

### ISSUE THREAD

**Issue by brianddk** [bitcoin-core/HWI#396]
Using the most basic form, in most cases a BIP16 P2SH scriptSig will be:

```
<signature> <<redeemScript>>
```
And for BIP141 witness program:

```
<signature> <<witnessScript>>
```

But BIP65 suggests more complex scripts which would require both signature data and arguments in the witness before the witnessScript.  How is this signaled to the `signtx` function, or how could it be signaled.  Is this even supported in PBST?  The specific script referenced in BIP65 gives an argument of `0` without Lenny's sig, or `1` with Lenny's sig.  Here's the script in greater detail:

#### witnessScript
```
    IF
        <now + 3 months> CHECKLOCKTIMEVERIFY DROP
        <Lenny's pubkey> CHECKSIGVERIFY
        1
    ELSE
        2
    ENDIF
    <Alice's pubkey> <Bob's pubkey> 2 CHECKMULTISIG
```

#### witness program (without Lenny)
```
    0 <Alice's signature> <Bob's signature> 0 <<witnessScript>>
```

#### witness program (with Lenny)
```
    0 <Alice/Bob's signature> <Lenny's signature> 1 <<witnessScript>>
```

In both cases there is either an `OP_0` or `OP_1` before the witnessScript which of course, only makes sense for this specific witnessScript.

So how would this special argument requirement be communicated to HWI, or how would it know to do anything other than `<signature> <<witnessScript>>` in the signing operation?

**Comment by achow101** [comment]
HWI doesn't handle those. As HWI only implements the signer role, knowing these arguments or adding them to the scriptSig/witness is not part of its responsibility. That is for the finalizer to deal with, which is some other software.

Those "extra arguments" aren't needed for creating the signatures, so there is no way to pass them to HWI nor does HWI need them to produce valid signatures for such inputs.
