### ISSUE TITLE
1.2.0 doesn't work on older macOS build

### ISSUE THREAD

**Issue by hugohn** [bitcoin-core/HWI#397]
I got this error running [1.2.0](https://github.com/bitcoin-core/HWI/releases/tag/1.2.0) on a macOS High Sierra (10.13.1):

```
$ ./hwi
[45254] Error loading Python lib '/var/folders/jh/drtb4sds3nv9k0438g4y9phh0000gn/T/_MEIkSp7gd/Python': dlopen: dlopen(/var/folders/jh/drtb4sds3nv9k0438g4y9phh0000gn/T/_MEIkSp7gd/Python, 10): Symbol not found: ____chkstk_darwin
  Referenced from: /var/folders/jh/drtb4sds3nv9k0438g4y9phh0000gn/T/_MEIkSp7gd/libintl.8.dylib (which was built for Mac OS X 10.15)
  Expected in: /usr/lib/libSystem.B.dylib
 in /var/folders/jh/drtb4sds3nv9k0438g4y9phh0000gn/T/_MEIkSp7gd/libintl.8.dylib
```

Rebuilt binary on 10.13.1 fixes it. It works both on 10.13.1 and latest macOS.

Binary attached here.

[hwi_mac_10_13_1.zip](https://github.com/bitcoin-core/HWI/files/5394473/hwi_mac_10_13_1.zip)

**Comment by achow101** [comment]
Hmm. I don't have a Mac with an older macOS so I can't test this. I suspect it's because it platform incompatibilities introduced by Apple that pyinstaller accidentally(?) includes.

**Comment by molnard** [comment]
Do you have a minimum system requirements docs for HWI? So as far as I can understand if HWI is built on an older system then it will work everywhere?

**Comment by nopara73** [comment]
I'd like to offer a bounty of about 100 USD (paid out in BTC) if someone could resolve this issue.

**Comment by hugohn** [comment]
In the mean time, our workaround for Nunchuk is to compile from source on an older Mac...

Binary for 1.2.1 (built on Mac OS 10.13.1): 
[hwi_mac_1_2_1.zip](https://github.com/bitcoin-core/HWI/files/5931385/hwi_mac_1_2_1.zip)

**Comment by prusnak** [comment]
JFYI Mac OS 10.13 is EOL since January 2021

**Comment by achow101** [comment]
For future releases, I'll do the build in a VM with an older MacOS version.

**Comment by molnard** [comment]
Let me know if you are done with it and ready for the bounty ;-)

**Comment by achow101** [comment]
I have updated my release process to use a MacOS 10.13 VM for the MacOS builds. Please test HWI 2.0.0-rc.2.

**Comment by molnard** [comment]
@achow101 awesome!

**Comment by nopara73** [comment]
FTR [the bounty](https://github.com/bitcoin-core/HWI/issues/397#issuecomment-739484267) is claimed by @achow101. Congrats! 🚀
