### ISSUE TITLE
Ledger Blue support?

### ISSUE THREAD

**Issue by RustWarfareElite** [bitcoin-core/HWI#398]
I am currently deploying a BTCPay Server for a project we are putting together soon. I was trying to figure out if my only hardware wallet the Ledger Blue would be a possible use for the wallet we plan to put with this server. I found out they are using your system here but only see Nano support.

Will there be full Ledger Blue support in the future or is it possible the Blue may work currently? I have found in the past that some Nano only supported apps and builds sometimes will work with the Blue but its a hit and miss. I got a few days before I am fully synced so looking at my options ahead of time in that hardware wallet area and any feedback or info in this area with HWI is appreciated.

I know its not a widely used device in the space due to its original high price and looks sold out and maybe even discontinued at this stage but curious if its been used at all with this

**Comment by achow101** [comment]
HWI is not tested with the Ledger Blue and there is currently no plan to officially support it as it appears to be a discontinued product.

**Comment by instagibbs** [comment]
NACK as well, it's a discontinued product that honestly never had real support from the parent company.
