### ISSUE TITLE
Ledger Nano X no longer works as of 1.5.1 app

### ISSUE THREAD

**Issue by Sjors** [bitcoin-core/HWI#402]
We're no longer seeing the device in `enumerate`:

```
./hwi.py --debug enumerate
DEBUG:hwilib.devices.trezorlib.transport:Enumerating UdpTransport: found 0 devices
DEBUG:hwilib.devices.trezorlib.transport:Enumerating HidTransport: found 0 devices
DEBUG:hwilib.devices.trezorlib.transport:Enumerating WebUsbTransport: found 0 devices
DEBUG:hwilib.devices.trezorlib.transport:Enumerating UdpTransport: found 0 devices
DEBUG:hwilib.devices.trezorlib.transport:Enumerating HidTransport: found 0 devices
DEBUG:hwilib.devices.trezorlib.transport:Enumerating WebUsbTransport: found 0 devices
[]
```

When the bitcoin app is closed on the device, it does throw an error as expected, so it seems there's at least some communication:

```
[{"type": "ledger", "model": "ledger_nano_x", "path": "0001:0006:00", "error": "Could not open client or get fingerprint information: get_pubkey_at_path canceled", "code": -14}]
```

It possible that this started happening in a slightly earlier version, since I haven't tested every release.

I also tried on a Nano S running 1.5.0: that still works. 

Unforuntately the app doesn't have release notes, so it's difficult to triangulate where the issue might be: https://github.com/LedgerHQ/app-bitcoin/tags

cc @btchip @TamtamHero

**Comment by TamtamHero** [comment]
This commit is the reason for this issue: https://github.com/LedgerHQ/app-bitcoin/commit/a486465d1242889e884046879016d3493940d449

USB PID have changed as described here, but we applied this change to bitcoin app just a few days ago: https://www.ledger.com/windows-10-update-sunsetting-u2f-tunnel-transport-for-ledger-devices

**Comment by SomberNight** [comment]
@TamtamHero Can you confirm this was the only relevant change in 1.5.1?
It seems to me now the device gives an error for pubkey requests when locked. Previously you could get an xpub from it even if locked.
A changelog would be nice.

**Comment by TamtamHero** [comment]
>  Can you confirm this was the only relevant change in 1.5.1?

I do confirm

> Previously you could get an xpub from it even if locked.

This behavior has been changed at least a few months ago, on the firmware side. It's not possible for an app to execute an operation that requires access to the seed when the device is locked.

> A changelog would be nice.

Absolutely nothing user facing, expect indirectly this USB PID upgrade, and support for the latest Zcash hard fork.

**Comment by SomberNight** [comment]
All right, thanks.

> This behavior has been changed at least a few months ago

that's why a changelog would be nice :)

**Comment by TamtamHero** [comment]
Indeed, noted :+1: 
Somehow we have changelogs on some repos (https://github.com/LedgerHQ/app-monero/blob/master/CHANGELOG.md), but not everywhere. We will harmonize this in the future, and we plan to display these logs in the manager of the Ledger Live as well :)
