### ISSUE TITLE
Bitbox02 failing type check

### ISSUE THREAD

**Issue by achow101** [bitcoin-core/HWI#422]
BitBox02 is failing the type checker: https://cirrus-ci.com/task/6500295159054336

cc @benma

**Comment by benma** [comment]
This particular issue is fixed in this commit:

https://github.com/bitcoin-core/HWI/pull/407/commits/c9c4d7540b4162f50c3fcf66321c1631f9c0cca5

I could extract it into a separate PR if you want.

**Comment by benma** [comment]
Thanks for merging the above commit.

In the meantime we released v5.2.0 with antiklepto support and a similar type signature change like in this issue:

https://github.com/bitcoin-core/HWI/pull/436

**Comment by instagibbs** [comment]
closing, let me know if there's something left undone
