### ISSUE TITLE
Segmentation Fault when using keyboard shortcuts - Ubuntu 20.04 - Trezor One - hwi-qt

### ISSUE THREAD

**Issue by spinza** [bitcoin-core/HWI#480]
I have imported my Trezor descriptors into Bitcoin Core 0.21.0 and have it running.

1. I startup `hwi-qt` from `hwi-2.0.0-rc.2-linux-amd64.tar.gz` and unlock the Trezor.
2. I create a test transaction to another Trezor address in the same wallet in Bitcoin Core.  The transactions is copied to clipboard.
3. I go back to `hwi-qt` and go to "Sign PSBT" and press `Ctrl + V` 
4. Results in Segmentation Fault

I played around with this and if I right click in the box and press the paste shortcut it works fine.  

Similarly when I wanted to use `Alt + Tab` to switch from `hwi-qt` it also has a segmentation fault just when I press `Alt` even before the `Tab`.

Additional keys causing issues on single press
* `Ctrl`
* `Alt`
* `Del`

The happens on the default opening window of `hwi-qt` too.  Doesn't have to be the Sign PSBT dialog.

Last lines on terminal:
```
Fontconfig error: "/etc/fonts/conf.d/80-delicious.conf", line 6: invalid attribute 'version'
Fontconfig warning: "/etc/fonts/conf.d/90-synthetic.conf", line 4: unknown element "its:rules"
Fontconfig warning: "/etc/fonts/conf.d/90-synthetic.conf", line 5: unknown element "its:translateRule"
Fontconfig error: "/etc/fonts/conf.d/90-synthetic.conf", line 5: invalid attribute 'translate'
Fontconfig error: "/etc/fonts/conf.d/90-synthetic.conf", line 5: invalid attribute 'selector'
Fontconfig error: "/etc/fonts/conf.d/90-synthetic.conf", line 6: invalid attribute 'xmlns:its'
Fontconfig error: "/etc/fonts/conf.d/90-synthetic.conf", line 6: invalid attribute 'version'
Fontconfig error: Cannot load default config file
libGL error: MESA-LOADER: failed to open iris (search paths /usr/lib/x86_64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri)
libGL error: failed to load driver: iris
libGL error: MESA-LOADER: failed to open swrast (search paths /usr/lib/x86_64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri)
libGL error: failed to load driver: swrast
Segmentation fault (core dumped)
```

**Comment by achow101** [comment]
It seems like this problem is due to pyinstaller. When I run the `hwi-qt.py` script directly, there's no such issue. Only when I use the pyinstaller build does it crash.

I'm not sure if there is anything that we can do about this. I'll keep investigating.

**Comment by spinza** [comment]
One thing I would then add is how to run from source.  I don't think `hwi-qt.py` is not documented in the `README.md`.  There are additional requirements.
