### ISSUE TITLE
Ledger: Cannot open client or get fingerprint information

### ISSUE THREAD

**Issue by eszoke** [bitcoin-core/HWI#482]
I seem to be having the same issue that is posted [here](https://github.com/bitcoin-core/HWI/issues/271), however the steps to resolve said issue in that case, I am having no luck with yet.

When I enumerate I get the following output:
`[{"type": "ledger", "model": "ledger_nano_x", "path": "0008:0006:00", "error": "Could not open client or get fingerprint information: open failed", "code": -13}]`

The Ledger is unlocked and the Bitcoin app is opened and ready. All of the udev rules have been copied over to /etc/udev/rules.d/.

I know the last release contained a fix for what was the latest Ledger firmware. Could another firmware update have messed something up? Or am I still missing something else perhaps?

Thank you!

**Comment by instagibbs** [comment]
nothing should have changed with respect to simple enumerate, afaik

**Comment by instagibbs** [comment]
Can you try previous releases to see if it happens there too?

**Comment by DariusParvin** [comment]
I'm getting a similar error to the above, but slightly different:
```
[{"type": "ledger", "model": "ledger_nano_s", "path": "IOService:/AppleACPIPlatformExpert/PCI0@0/AppleACPIPCI/XHC1@14/XHC1@14000000/HS08@14300000/USB2.0 Hub             @14300000/AppleUSB20Hub@14300000/AppleUSB20HubPort@14320000/4-Port USB 2.0 Hub@14320000/AppleUSB20Hub@14320000/AppleUSB20HubPort@14324000/Nano S@14324000/Nano S@0/AppleUserUSBHostHIDDevice", "error": "Could not open client or get fingerprint information: Exception : Invalid status 6e00", "code": -13}]
```

When I try with an older hwi release (1.2.1) it seems to work, I get:
```
[{"type": "ledger", "model": "ledger_nano_s", "path": "IOService:/AppleACPIPlatformExpert/PCI0@0/AppleACPIPCI/XHC1@14/XHC1@14000000/HS08@14300000/USB2.0 Hub             @14300000/AppleUSB20Hub@14300000/AppleUSB20HubPort@14320000/4-Port USB 2.0 Hub@14320000/AppleUSB20Hub@14320000/AppleUSB20HubPort@14324000/Nano S@14324000/Nano S@0/AppleUserUSBHostHIDDevice", "fingerprint": "fdda057b", "needs_pin_sent": false, "needs_passphrase_sent": false}]
```

**Comment by achow101** [comment]
@DariusParvin What version of the bitcoin app? The error code 6e00 corresponds to `BTCHIP_SW_CLA_NOT_SUPPORTED` which sounds like a version incompatibility problem.

**Comment by DariusParvin** [comment]
@achow101 I'm running Ledger Live 2.8.0.  I see now that there's version 2.32.2 version though, so I'll upgrade to that and try again. Thanks!

**Comment by achow101** [comment]
The version of ledger live shouldn't matter, just what is running on the ledger itself.

**Comment by DariusParvin** [comment]
The firmware is version 1.4.2 and MCU is 1.5 . I see firmware 1.6 is available so i'll upgrade to that.

**Comment by DariusParvin** [comment]
okay great it's working now and I'm running hwi 2.0.2.  What i'm finding though is that it only works the first time I open the bitcoin app. As in when I open the bitcoin app on the ledger and run `./hwi.py enumerate`, the first time i get:

```
[{"type": "ledger", "model": "ledger_nano_s", "path": "IOService:/AppleACPIPlatformExpert/PCI0@0/AppleACPIPCI/XHC1@14/XHC1@14000000/HS08@14300000/USB2.0 Hub             @14300000/AppleUSB20Hub@14300000/AppleUSB20HubPort@14320000/4-Port USB 2.0 Hub@14320000/AppleUSB20Hub@14320000/AppleUSB20HubPort@14324000/Nano S@14324000/Nano S@0/AppleUserUSBHostHIDDevice", "fingerprint": "fdda057b", "needs_pin_sent": false, "needs_passphrase_sent": false}]
```

but then if I run `./hwi.py enumerate` again (while still keeping the bitcoin app on the ledger open), I get:
```
[{"type": "ledger", "model": "ledger_nano_s", "path": "IOService:/AppleACPIPlatformExpert/PCI0@0/AppleACPIPCI/XHC1@14/XHC1@14000000/HS08@14300000/USB2.0 Hub             @14300000/AppleUSB20Hub@14300000/AppleUSB20HubPort@14320000/4-Port USB 2.0 Hub@14320000/AppleUSB20Hub@14320000/AppleUSB20HubPort@14324000/Nano S@14324000/Nano S@0/AppleUserUSBHostHIDDevice", "error": "Could not open client or get fingerprint information: open failed", "code": -13}]
```
If I close and reopen the bitcoin app on the ledger then it works again. Just wanted to check if that's expected behavior?

**Comment by DariusParvin** [comment]
okay I realize what the problem was. I think it's because I had the Ledger Live app open as well. When I close that now I have no issues. Thanks
