### ISSUE TITLE
Commands fail when Bitbox02 is displaying an address

### ISSUE THREAD

**Issue by craigraw** [bitcoin-core/HWI#486]
While Bitbox02 is displaying an address (before the 'tick' is touched to clear the address), all HWI commands fail.

Here is the output from `enumerate`:
```
❯ ./hwi enumerate
Traceback (most recent call last):
  File "hwi.py", line 7, in <module>
  File "hwilib/_cli.py", line 305, in main
  File "hwilib/_cli.py", line 269, in process_commands
  File "hwilib/_cli.py", line 62, in enumerate_handler
  File "hwilib/commands.py", line 113, in enumerate
  File "hwilib/devices/bitbox02.py", line 182, in enumerate
  File "hwilib/devices/bitbox02.py", line 271, in __init__
  File "hid.pyx", line 74, in hid.device.open_path
OSError: open failed
```

**Comment by achow101** [comment]
This usually means that you don't have the udev rules installed.

**Comment by craigraw** [comment]
This is on OSX. 

There is a difference in how devices handle the `displayaddress` command - on Coldcard, the command returns immediately, while on Trezor and Bitbox02, hwi waits until the user completes the address acknowledgement on the device before returning. I assume this is because those devices don't return the address until this has been done, so hwi can't display it as the command output. However, if hwi is called in another process (as an application may do) while the `displayaddress` command is still waiting for the user acknowledgement, that second command fails as above.

This interactivity requirement seems a bit different from most other hwi commands - it would be nice to have a way to turn it off. Certainly I don't need hwi to tell me the address, just to display it on the device for the user to confirm.

**Comment by achow101** [comment]
It depends on the device and it's library. In some devices, a response isn't sent until the user does something on the device. There's nothing we can do about that.

**Comment by craigraw** [comment]
> Edit: Are you saying that this error happens if you don't do anything on device?

Yes, when the address is displayed on the device, and the user hasn't done anything. HWI is waiting for the user acknowledgement on the device to receive the address.

**Comment by achow101** [comment]
I'm unable to reproduce. It just hangs indefinitely and never times out to an error.

**Comment by craigraw** [comment]
> However, if hwi is called in another process (as an application may do) while the displayaddress command is still waiting for the user acknowledgement, that second command fails as above.

This may not have been clear enough - I'm referring to a second invocation of hwi, while the first is hanging indefinitely. My hope is that it's possible to avoid the hanging situation on `displayaddress` entirely, but as I said, if the device is going to fail to respond to commands anyway before the address is cleared off it's screen, then the current behaviour is correct.

**Comment by achow101** [comment]
Ah I see. This is expected behavior because one instance of HWI is already communicating with the device, so another instance that tries to communicate with it will fail to get a handle.
