### ISSUE TITLE
Use of sortedmulti in displayaddress descriptor produces inconsistent results

### ISSUE THREAD

**Issue by craigraw** [bitcoin-core/HWI#487]
According to [descriptors.md](https://github.com/bitcoin/bitcoin/blob/master/doc/descriptors.md), the use of `sortedmulti` should mean that "the order of public keys in the resulting witnessScripts is determined by the lexicographic order of the public keys at that index" (this for a `wsh` descriptor).

This suggests that using `sortedmulti` should mean calling `displayaddress` with the provided xpub/childpubkeypaths out of BIP67 ordering should result in the correct address being displayed according to BIP67. However, there are inconsistent results:
- Bitbox02 displays the correct address regardless of xpub ordering
- Trezor sometimes displays an incorrect address (possibly depending on whether the keys are already sorted?)
- Coldcard fails every time with `{"error": "Coldcard Error: BIP67 violation", "code": -7}` - even if the xpubs are in the correct order. Changing `sortedmulti` to `multi` fixes this.

**Comment by prusnak** [comment]
> * Trezor sometimes displays an incorrect address (possibly depending on whether the keys are already sorted?)

Trezor always sorts pubkeys in scripts according to BIP67. Thus unsorted multi will not work on Trezor as expected.

BIP67 is for sorting scripts within the redeem script, not for sorting xpubs.

**Comment by achow101** [comment]
> * Coldcard fails every time with `{"error": "Coldcard Error: BIP67 violation", "code": -7}` - even if the xpubs are in the correct order. Changing `sortedmulti` to `multi` fixes this.

Are you sure that it is `sortedmulti` that doesn't work? The tests used `sortedmulti` and Coldcard only supports BIP 67 ordering, so `sortedmulti` should work and `multi` should not.

**Comment by achow101** [comment]
> > * Trezor sometimes displays an incorrect address (possibly depending on whether the keys are already sorted?)
> 
> Trezor always sorts pubkeys in scripts according to BIP67. Thus unsorted multi will not work on Trezor as expected.
> 
> BIP67 is for sorting scripts within the redeem script, not for sorting xpubs.

It doesn't seem like it though. The displayaddress test for xpubs in multisigs fails if the `multi` is changed to `sortedmulti`. The address the trezor produces disagrees with the address that bitcoind produces for the `sortedmulti`. If I use `sortedmulti` for the trezor, and `multi` for bitcoind (same key in the same order), then the test passes. This would seem to indicate that the device is not sorting the derived child keys properly.

**Comment by prusnak** [comment]
Ah, sorry, I got confused. We do sort the keys, but only for internal purposes of duplicate checking. The keys within the redeemscript are not sorted.
