### ISSUE TITLE
Command sendpin fails on Trezor One where passphrase is required

### ISSUE THREAD

**Issue by craigraw** [bitcoin-core/HWI#489]
On Trezor One devices where the `togglepassphrase` command has been used to require keyboard passphrase entry, the `sendpin` command fails:
```
❯ ./hwi.py --device-path "webusb:xxxxxx" --device-type "trezor" sendpin 12345678
{"error": "get_passphrase() got an unexpected keyword argument 'available_on_device'", "code": -13}
```
The device does however display 'Please enter your passphrase using the computer's keyboard.', so it appears the pin entry was successful. Firmware version is 1.9.4.

**Comment by prusnak** [comment]
I think this was already fixed via https://github.com/bitcoin-core/HWI/pull/481

**Comment by craigraw** [comment]
The testing was done with HEAD (changes from #481 included).

**Comment by craigraw** [comment]
Confirmed using a Windows build of latest master as well. I've had user reports that the Trezor T is also affected (I don't have one to test with).
