### ISSUE TITLE
Command installudevrules fails when udevadm is not in /sbin

### ISSUE THREAD

**Issue by craigraw** [bitcoin-core/HWI#491]
Ubuntu 20.04.1 places `udevadm` in `/usr/bin/` rather than `/sbin`, causing `installudevrules` to fail with
```
{"error": "installudevrules failed: [Errno 2] No such file or directory: '/sbin/udevadm'", "code": -13}
```

Ideally, hwi would detect the location with `which udevadm` before calling it (and `groupadd` and `usermod` as well).

**Comment by prusnak** [comment]
[`shutil.which`](https://docs.python.org/3/library/shutil.html#shutil.which) might be used to discover the binaries:

in `hwilib/udevinstaller.py`:

``` patch
     def __init__(self) -> None:
-        self._udevadm = '/sbin/udevadm'
-        self._groupadd = '/usr/sbin/groupadd'
-        self._usermod = '/usr/sbin/usermod'
+        self._udevadm = shutil.which('udevadm')
+        self._groupadd = shutil.which('groupadd')
+        self._usermod = shutil.which('usermod')
 
```
