### ISSUE TITLE
Taproot support

### ISSUE THREAD

**Issue by Sjors** [bitcoin-core/HWI#501]
Afaik none of the hardware wallets we support currently has even a draft implementation of Taproot. But we can update this issue when that happens.

**Comment by yeru83** [comment]
Not sure here, but as of July, there Appears to be some progress in the BotBox02, as of April
https://github.com/bitcoin-core/HWI/search?q=taproot

**Comment by prusnak** [comment]
Tracking issue for Trezor Taproot Support: https://github.com/trezor/trezor-firmware/issues/1656

**Comment by craigraw** [comment]
Ledger appears to have Taproot support now: https://blog.ledger.com/taproot-support/

Also, it appears HWI does not support the `tr` script expression for displaying an address. HWI currently returns `tr is not a valid descriptor function` when a BIP386 Taproot output descriptor is used for the `--desc` argument.

**Comment by Sjors** [comment]
Great to hear that Ledger supports Taproot receive addresses.

**Comment by achow101** [comment]
> Ledger appears to have Taproot support now: https://blog.ledger.com/taproot-support/

Interesting. I wasn't able to find any technical docs for how to use Taproot on ledger devices.

> Also, it appears HWI does not support the `tr` script expression for displaying an address. HWI currently returns `tr is not a valid descriptor function` when a BIP386 Taproot output descriptor is used for the `--desc` argument.

This is currently in progress.

***

Trezor recently merged Taproot support for the Trezor T: https://github.com/trezor/trezor-firmware/pull/1891. The initial support PR will likely only include Trezor T support as it is the easiest one for me to find documentation for and test.

**Comment by Sjors** [comment]
cc @btchip @TamtamHero

**Comment by prusnak** [comment]
> Trezor recently merged Taproot support for the Trezor T: [trezor/trezor-firmware#1891](https://github.com/trezor/trezor-firmware/pull/1891). The initial support PR will likely only include Trezor T support as it is the easiest one for me to find documentation for and test.

Taproot for Trezor Model One is in this PR https://github.com/trezor/trezor-firmware/pull/1917 (soon to be merged). It should work the same way as on Trezor Model T, so if your HWI changes work with Trezor Model T, they should also work with the Trezor Model One. 

Both Trezor Model T and Trezor Model One firmwares with Taproot functionality will be released in the middle of December.

**Comment by gruve-p** [comment]
> Tracking issue for Trezor Taproot Support: [trezor/trezor-firmware#1656](https://github.com/trezor/trezor-firmware/issues/1656)

That one is closed and seperated into subtasks:
https://github.com/trezor/trezor-firmware/issues/1943
https://github.com/trezor/trezor-firmware/issues/1944
https://github.com/trezor/trezor-firmware/issues/1946

**Comment by prusnak** [comment]
> That one is closed and seperated into subtasks:
> [trezor/trezor-firmware#1943](https://github.com/trezor/trezor-firmware/issues/1943)
> [trezor/trezor-firmware#1944](https://github.com/trezor/trezor-firmware/issues/1944)
> [trezor/trezor-firmware#1946](https://github.com/trezor/trezor-firmware/issues/1946)

That is not entirely correct. Taproot for singlesig has been implemented. The tasks you linked were created for remaining stuff not related to singlesig (such as message signing, ownership proofs and multisig).

**Comment by Sjors** [comment]
Closing this, since at least some wallets now have basic Taproot keypath support.

Shameless plug for https://github.com/bitcoin/bitcoin/pull/23578 which adds Bitcoin Core support for importing keypath descriptors from an external signer.
