### ISSUE TITLE
scantxoutset helper

### ISSUE THREAD

**Issue by Sjors** [bitcoin-core/HWI#51]
This should make it easier to check if there are any unspent funds without having to sit through a long rescan.

```
./hwi.py --device-type=ledger scantxoutset --bech32 [--paths [desc1 desc2 desc3 etc]] [range=1000]
```

It would use BIP44/49/84 by default and produce descriptors for both receive and change chains.

**Comment by instagibbs** [comment]
> descriptors for both receive and change chains

Related: should we do this for getkeypool as well?

**Comment by achow101** [comment]
`getdescriptors` was added a while back, so I think this can be closed.
