### ISSUE TITLE
--chain does not seem to work

### ISSUE THREAD

**Issue by NicolasDorier** [bitcoin-core/HWI#513]
tried on 2.0.1 on my ledger:

`hwi.exe --chain regtest --fingerprint xxxxxxxx displayaddress --path m/44h/1h/0h/0/1 --addr-type legacy`

This does not show me regtest addresses. Testnet is not better. Tried on coldcard as well, no effect.

**Comment by achow101** [comment]
On some devices, `--chain` is a lie. This could be better communicated.

Coldard and Ledgers have on device chain modes. You have to be in those to get addresses for different chains. Coldcard has a setting somewhere for that. On Ledgers you need to have the Bitcoin Testnet app.

**Comment by NicolasDorier** [comment]
it make sense. I am surprised, could have sworn that at some point it was not a lie for ledger wallet.
