### ISSUE TITLE
Keep Key HWI issue?

### ISSUE THREAD

**Issue by cAP5L0CK** [bitcoin-core/HWI#526]
Seeing issues with the Keep Key in multiple software at the point of sending the passphrase.  This happens in Specter as well as Sparrow wallets almost identically.  The Sparrow developer pointed me here as he suspects the issue may be in HWI which both wallets use.  Electrum does not have this issue.

In Specter it the error looks like this:
![image](https://user-images.githubusercontent.com/11202204/134816369-5e738f22-af80-4c80-90a1-381de218c280.png)

And in Sparrow we see something similar:
![image](https://user-images.githubusercontent.com/11202204/134816384-0a28ab5b-ab5e-453e-b8bd-d4c8a2712258.png)

This is with the latest KeepKey firmware (7.2.1).  And I have reproduced the issue on both Windows 10 and Arch Linux. Electrum does not have this issue with the KeepKey and works properly.  I do not know if it used HWI.  

Here are the respective posts for both of these wallets:
https://github.com/cryptoadvance/specter-desktop/issues/1219
https://github.com/sparrowwallet/sparrow/issues/219

(strange they both end in 219? ;) )

Anyway.  Is this the right place to report the issue?

**Comment by achow101** [comment]
It looks like a change was introduced to the keepkey firmware that is incompatible with HWI. Looking into it.
