### ISSUE TITLE
doc: Ledger dependencies missing from test/README

### ISSUE THREAD

**Issue by Sjors** [bitcoin-core/HWI#569]
On Ubuntu 21.10 I had to add (but I already had some stuff for other emulators):

```sh
sudo apt-get install gcc-arm*
```

**Comment by Sjors** [comment]
Unfortunately when I do `poetry run ./run_tests.py --ledger` it just stalls (until I interrupt it).

```
...
test_rules_file_are_copied (test_udevrules.TestUdevRulesInstaller) ... ok

----------------------------------------------------------------------
Ran 23 tests in 3.460s

OK
^CTraceback (most recent call last):
  File "/home/dev/HWI/test/./run_tests.py", line 115, in <module>
    success &= ledger_test_suite(args.ledger_path, rpc, userpass, args.interface)
  File "/home/dev/HWI/test/test_ledger.py", line 123, in ledger_test_suite
    dev_emulator.start()
  File "/home/dev/HWI/test/test_ledger.py", line 47, in start
    time.sleep(0.5)
KeyboardInterrupt
```

**Comment by achow101** [comment]
You need to install several additional python packages for speculos to work:

    pip install construct flask-restful jsonschema mnemonic pyelftools pillow requests

**Comment by Sjors** [comment]
That results in a flood of "Requirement already satisfied", but maybe I installed these in the interim. Tests are running now.
