### ISSUE TITLE
FloatOperation in btchipHelpers.py

### ISSUE THREAD

**Issue by St333p** [bitcoin-core/HWI#575]
Importing `HWI` in my project causes a crash caused by a `decimal.Decimal.FloatOperation` on line 24 of `hwilib/devices/btchip/btchipHelpers.py`. It is caused by the conversion of a float into a decimal in `Decimal(1e8)`.

Since importing the library in a python shell in the same virtualenv does work correcly, the issue lies on my side and I'm currently looking into Decimal configurations in my project that might affect this. Nonetheless, I think changing it to `Decimal(10**8)` would be cleaner. Sorry if this was already discussed, I was not able to find any issues on the matter.

**Comment by brunoerg** [comment]
I think this issue can be closed since it is solved. See: https://github.com/bitcoin-core/HWI/pull/698

cc: @achow101
