### ISSUE TITLE
Using macOS 10.15 for Mac release builds?

### ISSUE THREAD

**Issue by achow101** [bitcoin-core/HWI#589]
#397 was resolved by using macOS 10.13 for making the release builds. However when making 2.1.0-rc.1, I ran into issues with using 10.13 and 10.14 for the release. rc1 was released using 10.15.

Do people still use 10.13? Should I try to fix the build issues or is it reasonable to move to 10.15 for new releases?

***

The issues seem related to pyinstaller and some apple built in tools not working as expected.

**Comment by prusnak** [comment]
Anything older than 10.15 is EOL: https://endoflife.date/macos

**Comment by gruve-p** [comment]
Sounds reasonable to move to 10.15 for new releases.

**Comment by craigraw** [comment]
Fwiw I rebuild HWI (using `--onedir`) on macOS 10.13 as Sparrow users still request it. Published EOLs aside, Macs tend to have a long operating life and older ones cannot be updated to the latest OS.

**Comment by achow101** [comment]
Whatever issue I was having with this seems to have gone away.
