### ISSUE TITLE
Taproot signature issues using Trezor

### ISSUE THREAD

**Issue by craigraw** [bitcoin-core/HWI#591]
I am testing Taproot support in HWI 2.1.0-rc1 against a Trezor One running the latest firmware (1.10.5).

I've run into two issues:
1. HWI in https://github.com/bitcoin-core/HWI/blob/f0021502d470660b9d8a5e79fcc440ac809a610f/hwilib/devices/trezor.py#L624 is adding the Taproot key spend signature to the PSBT_IN_PARTIAL_SIG entries (in contravention to BIP174 which only accepts ECDSA signatures in that field).
2. I can't get the signature generated by Trezor to verify against the output key. This may be some error on my part, but I am able to get PSBTs with Taproot key spend signatures generated by software wallets in Sparrow to verify (and later successfully broadcast in the extracted transaction). The Schnorr signature returned from Trezor parses fine, but when I try to broadcast the extracted transaction with this signature, I get `non-mandatory-script-verify-flag (Invalid Schnorr signature)`.

**Comment by achow101** [comment]
>  1. HWI in https://github.com/bitcoin-core/HWI/blob/f0021502d470660b9d8a5e79fcc440ac809a610f/hwilib/devices/trezor.py#L624
>  is adding the Taproot key spend signature to the PSBT_IN_PARTIAL_SIG entries (in contravention to BIP174 which only accepts ECDSA signatures in that field).

It shouldn't be unless your PSBT incorrectly contains taproot key entries in PSBT_IN_BIP32_DERIVATION.

> 2. I can't get the signature generated by Trezor to verify against the output key. This may be some error on my part, but I am able to get PSBTs with Taproot key spend signatures generated by software wallets in Sparrow to verify (and later successfully broadcast in the extracted transaction). The Schnorr signature returned from Trezor parses fine, but when I try to broadcast the extracted transaction with this signature, I get `non-mandatory-script-verify-flag (Invalid Schnorr signature)`.

Can you provide an example PSBT?

**Comment by craigraw** [comment]
> It shouldn't be unless your PSBT incorrectly contains taproot key entries in PSBT_IN_BIP32_DERIVATION.

I see - should BIP 174 not mention this? I couldn't find any reference to it, although it does make sense to not repeat information already provided in PSBT_IN_TAP_BIP32_DERIVATION.

> Can you provide an example PSBT?

Finalized PSBT attached.

[TrezorTaproot.psbt.txt](https://github.com/bitcoin-core/HWI/files/8401956/TrezorTaproot.psbt.txt)

**Comment by achow101** [comment]
I can't find anything that would cause this problem, and we do have tests for this. Are you able to consistently reproduce this failure?

**Comment by craigraw** [comment]
I am able to reproduce this consistently on HWI 2.1.0 final using both a Trezor One and a Trezor T, both using latest firmware 1.10.5 and 2.4.3.

Here is an input PSBT passed into the Trezor with HWI for signing:
```
cHNidP8BAH0CAAAAAbHISBwns8hZucRVOQaSDfFFNg0rKaTt1Bmu3B1yKHbrAQAAAADBdQAAAh8ZAAAAAAAAIlEgXUMrkGKvNAPHv1RCzirjo/jClzqB5dtrZhXt8ZnIAkFnAwAAAAAAABYAFBXRCEXR6Rl1MwisYRFuPXYK9cUCAAAAAE8BBDWHzwNBGkUIgAAAALyxYn/OAHT/jwdvincS0I87PL9LXJVl8JPAOYh9nDiZAo+Yps7Np0OZCh1l+OvTZ3bYr06cHnlJ3e7e2p9Vyf2OEMqaKxlWAACAAQAAgAAAAIAAAQB9AgAAAAFZhyNDh8Itz/q10sgjOQeuINB4NLF/GzCvc2oVwkrAkQAAAAAA/f///wIOtAIAAAAAABYAFLT7WM2n1PmciTYVg9nyXF5+2uYRFR0AAAAAAAAiUSDmrGZVJO+NsziRvqr1JKd+q+jDjhJJX38OPsqsc1/BiQ1yIQABASsVHQAAAAAAACJRIOasZlUk742zOJG+qvUkp36r6MOOEklffw4+yqxzX8GJAQMEAAAAACEW+8GNZYQPLQrNd7WO9k+rvIZRNVcJPV5Nx0PaTgoUav4ZAMqaKxlWAACAAQAAgAAAAIAAAAAAAAAAAAEXIPvBjWWEDy0KzXe1jvZPq7yGUTVXCT1eTcdD2k4KFGr+ACICAnJwRcvKbID8/6ix+b9QUvheFdRqHQSpj9KSh/D8rSfJGMqaKxlWAACAAQAAgAAAAIABAAAAAAAAAAAA
```

Which parses as follows:

```
Transaction with txid: 347df901a911fcf1b2a490dccec88fb3a8a1b5fb6ed632359c0bc94fb212e276 version 2 size 125 locktime 0
 Transaction input references txid: eb7628721ddcae19d4eda4292b0d3645f10d92063955c4b959c8b3271c48c8b1 vout 1 with script 
 Transaction output value: 6431 to addresses [tb1pt4pjhyrz4u6q83al23pvu2hr50uv99e6s8jak6mxzhklrxwgqfqs7ck9em] with script hex 51205d432b9062af3403c7bf5442ce2ae3a3f8c2973a81e5db6b6615edf199c80241 to script OP_1 5d432b9062af3403c7bf5442ce2ae3a3f8c2973a81e5db6b6615edf199c80241
 Transaction output value: 871 to addresses [tb1qzhgss3w3ayvh2vcg43s3zm3awc90t3gzelk574] with script hex 001415d10845d1e919753308ac61116e3d760af5c502 to script OP_0 15d10845d1e919753308ac61116e3d760af5c502
Pubkey with master fingerprint ca9a2b19 at path m/86'/1'/0': tpubDCW9oAtxb2kE98t3KRjUFvWZsM2gkE7zc8EtVYyRkZL4XZ1Aee8PLZLasfBaSTApD5U8S2AghzxYtbbtqrzHrr5onHHRd42ZbEvFLqhLWEK
Found input non witness utxo with txid: eb7628721ddcae19d4eda4292b0d3645f10d92063955c4b959c8b3271c48c8b1 version 2 size 125 locktime 2191885
 Transaction input references txid: 91c04ac2156a73af301b7fb13478d020ae073923c8d2b5facf2dc28743238759 vout 0 with script 
 Transaction output value: 177166 to address tb1qkna43nd86nueezfkzkpanujuteld4es3ayutdf with script hex 0014b4fb58cda7d4f99c89361583d9f25c5e7edae611 to script OP_0 b4fb58cda7d4f99c89361583d9f25c5e7edae611
 Transaction output value: 7445 to address tb1pu6kxv4fya7xmxwy3h6402f9806473suwzfy47lcw8m92cu6lcxysn8m6pd with script hex 5120e6ac665524ef8db33891beaaf524a77eabe8c38e12495f7f0e3ecaac735fc189 to script OP_1 e6ac665524ef8db33891beaaf524a77eabe8c38e12495f7f0e3ecaac735fc189
Found input witness utxo amount 7445 script hex 5120e6ac665524ef8db33891beaaf524a77eabe8c38e12495f7f0e3ecaac735fc189 script OP_1 e6ac665524ef8db33891beaaf524a77eabe8c38e12495f7f0e3ecaac735fc189 addresses [tb1pu6kxv4fya7xmxwy3h6402f9806473suwzfy47lcw8m92cu6lcxysn8m6pd]
Found input sighash_type All (Taproot)
Found input taproot key derivation for key fbc18d65840f2d0acd77b58ef64fabbc86513557093d5e4dc743da4e0a146afe with master fingerprint ca9a2b19 at path m/86'/1'/0'/0/0
Found input taproot internal key fbc18d65840f2d0acd77b58ef64fabbc86513557093d5e4dc743da4e0a146afe
Found output bip32_derivation with master fingerprint ca9a2b19 at path m/86'/1'/0'/1/0 public key 02727045cbca6c80fcffa8b1f9bf5052f85e15d46a1d04a98fd29287f0fcad27c9
```

Here is the output PSBT returned by Trezor via HWI:
```
cHNidP8BAH0CAAAAAbHISBwns8hZucRVOQaSDfFFNg0rKaTt1Bmu3B1yKHbrAQAAAADBdQAAAh8ZAAAAAAAAIlEgXUMrkGKvNAPHv1RCzirjo/jClzqB5dtrZhXt8ZnIAkFnAwAAAAAAABYAFBXRCEXR6Rl1MwisYRFuPXYK9cUCAAAAAE8BBDWHzwNBGkUIgAAAALyxYn/OAHT/jwdvincS0I87PL9LXJVl8JPAOYh9nDiZAo+Yps7Np0OZCh1l+OvTZ3bYr06cHnlJ3e7e2p9Vyf2OEMqaKxlWAACAAQAAgAAAAIAAAQB9AgAAAAFZhyNDh8Itz/q10sgjOQeuINB4NLF/GzCvc2oVwkrAkQAAAAAA/f///wIOtAIAAAAAABYAFLT7WM2n1PmciTYVg9nyXF5+2uYRFR0AAAAAAAAiUSDmrGZVJO+NsziRvqr1JKd+q+jDjhJJX38OPsqsc1/BiQ1yIQABASsVHQAAAAAAACJRIOasZlUk742zOJG+qvUkp36r6MOOEklffw4+yqxzX8GJAQMEAAAAAAETQFw+rLe03in9Os88qTjQP5UzUXL9oJF6XbECPuoGliC0IFYx+0W20652fUnb8GogyQk7wcQ+W7d0C3bZjTtz71QhFvvBjWWEDy0KzXe1jvZPq7yGUTVXCT1eTcdD2k4KFGr+GQDKmisZVgAAgAEAAIAAAACAAAAAAAAAAAABFyD7wY1lhA8tCs13tY72T6u8hlE1Vwk9Xk3HQ9pOChRq/gAiAgJycEXLymyA/P+osfm/UFL4XhXUah0EqY/Skofw/K0nyRjKmisZVgAAgAEAAIAAAACAAQAAAAAAAAAAAA==
```

It parses as follows:
```
Transaction with txid: 347df901a911fcf1b2a490dccec88fb3a8a1b5fb6ed632359c0bc94fb212e276 version 2 size 125 locktime 0
 Transaction input references txid: eb7628721ddcae19d4eda4292b0d3645f10d92063955c4b959c8b3271c48c8b1 vout 1 with script 
 Transaction output value: 6431 to addresses [tb1pt4pjhyrz4u6q83al23pvu2hr50uv99e6s8jak6mxzhklrxwgqfqs7ck9em] with script hex 51205d432b9062af3403c7bf5442ce2ae3a3f8c2973a81e5db6b6615edf199c80241 to script OP_1 5d432b9062af3403c7bf5442ce2ae3a3f8c2973a81e5db6b6615edf199c80241
 Transaction output value: 871 to addresses [tb1qzhgss3w3ayvh2vcg43s3zm3awc90t3gzelk574] with script hex 001415d10845d1e919753308ac61116e3d760af5c502 to script OP_0 15d10845d1e919753308ac61116e3d760af5c502
Pubkey with master fingerprint ca9a2b19 at path m/86'/1'/0': tpubDCW9oAtxb2kE98t3KRjUFvWZsM2gkE7zc8EtVYyRkZL4XZ1Aee8PLZLasfBaSTApD5U8S2AghzxYtbbtqrzHrr5onHHRd42ZbEvFLqhLWEK
Found input non witness utxo with txid: eb7628721ddcae19d4eda4292b0d3645f10d92063955c4b959c8b3271c48c8b1 version 2 size 125 locktime 2191885
 Transaction input references txid: 91c04ac2156a73af301b7fb13478d020ae073923c8d2b5facf2dc28743238759 vout 0 with script 
 Transaction output value: 177166 to address tb1qkna43nd86nueezfkzkpanujuteld4es3ayutdf with script hex 0014b4fb58cda7d4f99c89361583d9f25c5e7edae611 to script OP_0 b4fb58cda7d4f99c89361583d9f25c5e7edae611
 Transaction output value: 7445 to address tb1pu6kxv4fya7xmxwy3h6402f9806473suwzfy47lcw8m92cu6lcxysn8m6pd with script hex 5120e6ac665524ef8db33891beaaf524a77eabe8c38e12495f7f0e3ecaac735fc189 to script OP_1 e6ac665524ef8db33891beaaf524a77eabe8c38e12495f7f0e3ecaac735fc189
Found input witness utxo amount 7445 script hex 5120e6ac665524ef8db33891beaaf524a77eabe8c38e12495f7f0e3ecaac735fc189 script OP_1 e6ac665524ef8db33891beaaf524a77eabe8c38e12495f7f0e3ecaac735fc189 addresses [tb1pu6kxv4fya7xmxwy3h6402f9806473suwzfy47lcw8m92cu6lcxysn8m6pd]
Found input sighash_type All (Taproot)
Found input taproot key path signature 5c3eacb7b4de29fd3acf3ca938d03f95335172fda0917a5db1023eea069620b4205631fb45b6d3ae767d49dbf06a20c9093bc1c43e5bb7740b76d98d3b73ef54
Found input taproot key derivation for key fbc18d65840f2d0acd77b58ef64fabbc86513557093d5e4dc743da4e0a146afe with master fingerprint ca9a2b19 at path m/86'/1'/0'/0/0
Found input taproot internal key fbc18d65840f2d0acd77b58ef64fabbc86513557093d5e4dc743da4e0a146afe
```

The signature does not verify against the output key.

**Comment by achow101** [comment]
What happens if you omit the sighash field?

**Comment by craigraw** [comment]
Same result when the sighash field is omitted from the input PSBT. Incidentally, the Trezor adds the sighash field on the output PSBT regardless.

**Comment by prusnak** [comment]
@craigraw You say you compare the Trezor result to a SW wallet. How about other HW wallets? Did they sign fine via HWI?

**Comment by achow101** [comment]
I was able to reproduce, and AFAICT, each party involved has a bug which contributes to this problem.

1. Your PSBT has `PSBT_OUT_BIP32_DERIVATION` for the taproot internal key of the change output. This is incorrect as that implies an ECDSA signature. It should be `PSBT_OUT_TAP_BIP32_DERIVATION`.
2. HWI sees the key in `PSBT_OUT_BIP32_DERIVATION` and sets the script type to `PAYTOWITNESS` instead of `PAYTOTAPROOT`. HWI could do some additional validation on this. It is also not searching the taproot derivation paths to correctly identify taproot change.
3. Trezor receives the `PAYTOWITNESS` and the derivation path for that change output and computes the wrong scriptPubKey. This thus results in the incorrect signature. However the `TxOutputType` has the correct address set, but it fails to validate that the computed scriptPubKey matches the given address.

**Comment by prusnak** [comment]
Thanks Andrew for investigating this!

**Comment by craigraw** [comment]
Thanks Andrew - this was indeed the cause, and I now that I've fixed the Sparrow side I can confirm that Taproot signing works on both Trezor One and T.

I also tested your change detection PR, and can confirm that it's fixes the issue of correctly detecting the change output for Taproot spends.

Closing this off.
