### ISSUE TITLE
Support Ledger Nano S Plus

### ISSUE THREAD

**Issue by ae33** [bitcoin-core/HWI#595]
The [official support page](https://hwi.readthedocs.io/en/latest/devices/index.html) specifies device support for the Ledger Nano S and Ledger Nano X, but not the newly released Ledger Nano S Plus.

When I try to run `hwi enumerate` after [installing HWI](https://hwi.readthedocs.io/en/latest/usage/installation.html) via `pip3 install hwi` on an Arch Linux build with a Ledger Nano S Plus plugged in via USB after initial device setup, it prints out `[]`. I would expect it to print out a single entry with device information. I propose adding support for Ledger's latest device.

This is my first time using HWI, and the Ledger Nano S Plus is my first and only hardware "wallet" device. So, I have no other means of testing out how HWI should behave when it works. From following the [example usage docs](https://hwi.readthedocs.io/en/latest/examples/bitcoin-core-usage.html) and observing the output, however, it would seem this device is not currently supported.

**Comment by rachyandco** [comment]
this also the case on Ubuntu 22.04 and hwi 2.1.0 using a Ledger Nano S Plus.
