### ISSUE TITLE
Micropython Support

### ISSUE THREAD

**Issue by maxdignan** [bitcoin-core/HWI#597]
I see that this needs a variety of USB libs to function and is written in Python3 (which I know isn't directly compatible with micropython by any means). What would it take to port this to be usable in a MicroPython environment?

**Comment by prusnak** [comment]
I am not saying this is impossible, but you'd need to reimplement lots of USB host stuff for Micropython.

What is your usecase?

**Comment by maxdignan** [comment]
For sure - and that would be pretty tough. The use case is to have a secure device - itself running micropython - interfacing with other hw wallets. Adds extra layer of security and other checks that technically aren't possible to do with assurances on an internet connected device, such as anti-exfiltration.

**Comment by laanwj** [comment]
>  in Python3 (which I know isn't directly compatible with micropython by any means)

FWIW Micropython is definitely based on Python 3 nowadays.

That said, yes it's going to be tons of porting work, some of which board specific (e.g. to the USB host controller core). I'm also of the opinion that maintaining this compatibility is not in scope of this project.
