### ISSUE TITLE
Ledger: Unable to sign transactions with mixed input types

### ISSUE THREAD

**Issue by achow101** [bitcoin-core/HWI#609]
If a transaction has multiple inputs of different script types, the device returns an error with status `0xb007`

**Comment by achow101** [comment]
This has been traced to an issue with the ledger app: https://github.com/LedgerHQ/app-bitcoin-new/issues/46

**Comment by bigspider** [comment]
The fix is released in version 2.0.6, just deployed. Thank you @achow101!
