### ISSUE TITLE
ClamAV/positives in hwi executable

### ISSUE THREAD

**Issue by pvig0q1s** [bitcoin-core/HWI#618]
Hello achow101,

I scanned some directories using clamav on linux.

hwi-2.1.x-linux-amd64/hwi gives a positive 'Unix.Dropper.Python-9950644-0' in the latest two builds, 2.1.1/2.1.0.

(positive) HWI 2.1.1 / May 24, 2022 ($ sha1sum hwi	3145c69f6ecb5ee4674ba523cdea980e91868662)
(positive) HWI 2.1.0 / Apr 15, 2022 ($ sha1sum hwi	7969241543249ca5be6085ac9724dbe8e3afb407)
(noresults) HWI 2.0.2 / Jun 01, 2021 ($ sha1sum hwi	1af735227e2d5d4aadb14b7ddd9b7591a8ffad40)

I came accross this reviewing sparrowwallet (@craigraw) which is using the same executables in 1.6.5 / 1.6.4 
/src/main/resources/native/linux/x64

Probably nothing, but since 2.0.2 is a year old and is returning no results I will leave this here.

Cheers!

**Comment by achow101** [comment]
This is a false positive. It's unclear to me what they are matching on, but there isn't much that can be done about that.
