### ISSUE TITLE
Multisig signing on Trezor T missing transaction details

### ISSUE THREAD

**Issue by Francisco-DAnconia** [bitcoin-core/HWI#620]
A new addition to HWI has detrimentally affected the use of the Trezor in multi-signature applications. 

I'm told this occurred when Sparrow updated HWI from 2.0.2 to 2.1.1. Testing was done use Sparrow 1.6.3 & 1.6.5 along with a Trezor Model T with firmwares: 2.43 & 2.5.1. 

The Trezor is a stateless hardware keystore. So, one cannot register co-signer XPUBs with the Trezor for a multi-signature wallet. This wasn't too bad with HWI 2.0.2 as the Trezor displayed for the user the relevant parts of the transaction. A paper list of internal and external addresses could be consulted for verification.

For example, consider this Testnet transaction:

- input 0 - 40,509 sats
- output 0 - external - 10,000 sats to tb1q54m7…
- output 1 - change - 30,320 sats to tb1qgvun…
- fee 189 sats

The Trezor connected via HWI 2.0.2 confirms all 6 pieces of TX data on it's confirmation screens:
![HWI 2 0 2](https://user-images.githubusercontent.com/33098368/178621253-3380c24f-e42b-44bf-9090-b53a4ca332d4.png)

In contrast the same transaction with HWI 2.1.1 shows only 3 pieces of TX data. It does **NOT** show: input of 40,509, change of 30,320 and the change address tb1qgvun…
![HWI 2 1 1](https://user-images.githubusercontent.com/33098368/178621393-17bef071-4bcd-4ac5-85a2-93701eaec9b2.png)

Also, it **_presumes_** to know the amount leaving the wallet of 10,189 along with a fee of 189. But it cannot _know_ this without access to the co-signer XPUBs. If malware lives on the connected computer, the undisplayed change address could be controlled by an attacker. A user could sign a transaction believing the change is safe when it is not. 

Is there anything that can be done to remedy this situation?

**Background**
Michael Flaxman (@mflaxman) has spoken and written on this specific attack surface: https://btcguide.github.io/known-issues/verify-receive-address

Another Multisignature pitfalls article: https://shiftcrypto.ch/blog/the-pitfalls-of-multisig-when-using-hardware-wallets/

> Once you managed to receive some coins securely, how can you spend them with confidence? The hardware wallet has to verify, or let you verify, the following information provided by the untrusted computer:
> 	•	The recipient’s address, displayed and confirmed by the user like with singlesig
> 	•	The change address, having the same cosigners and threshold in an ordinary multisig script with no other spending conditions
> 	•	The change goes to an address at a keypath recoverable by the user

**Comment by achow101** [comment]
The change detection is done with the co-signer xpubs. See #497 

It is not possible to mark a particular output as change from the software side. Rather all we can do is provide data to the Trezor which will determine what is change. As PSBTs can contain the co-signer xpubs, we can construct the multisig templates in use and provide them to the Trezor so that it can compute the correct addresses and detect change.

If you are finding that change is being improperly detected, this is likely an issue with the Trezor firmware - there is not much that HWI can do to inform the device about change.

**Comment by prusnak** [comment]
Yes. The address is hidden when it is a change address generated from the same set of keys that were used on the input side.

**Comment by mflaxman** [comment]
> Yes. The address is hidden when it is a change address generated from the same set of keys that were used on the input side. 

Not just same set of keys, but also threshold/quorum! For collaborative custodians (Casa/Unchained), going from 2-of-3 to 1-of-3 would be a major vulnerability! Last I checked Trezor has been handling this correctly for ~6 years in CHANGE validation (receive address validation is a separate thing outside the scope of this GitHub issue).

**Comment by prusnak** [comment]
> Not just same set of keys, but also threshold/quorum!

Yes, that's what I meant. Thanks!

**Comment by Francisco-DAnconia** [comment]
Well this looks to be a real education. Thanks.

> To be clear: the link you included from me was about RECEIVE address verification, which requires advanced verification skills (and/or separate hardware) when using a stateless device. CHANGE address verification is trivial for any decently written hardware wallet to handle automatically in software.

I assumed that generation of RECEIVE addresses and CHANGE addresses was a similar process of using the leaf public key as determined by the XPUBs & derivation path. But I must be missing something _significant_ if RECEIVE address verification is difficult with a stateless device, but CHANGE address verification is trivial. 

What am I missing?

### Mental Model
I'd surely appreciate it if someone can point out the mistake(s) in my mental model for multi-signature safety:

- Generate entropy, verify fingerprint and output descriptor on a trusted device screen. 
- Repeat for each device in multi-signature wallet. 
- Import the keystores into a coordinator (e.g. Sparrow/Spectre). 
- On hardware devices with state (e.g. Coldcard/Keystone) register the co-signer XPUBs and multi-signature wallet.
- On hardware devices with state, confirm XPUBs, are as expected with a trusted device.  Note also, policy & derivation paths.

I'm under the impression that by doing this, as long as the Coldcard/Keystone in question are not hacked, I can trust them to verify both RECEIVE addresses and CHANGE addresses. Even if the software wallet coordinator is malware compromised. Am I wrong?

The Trezor is stateless. It seems there is an implicit trust of the PSBT, w/o corresponding confirmation on a trusted display. And with HWI 2.1.1 the information displayed on the trusted display is reduced. If the software wallet coordinator is malware compromised, am I in a different situation on the Trezor than on the Coldcard/Keystone?

If there are resources that address this or a better forum for this discussion, please let me know.

**Comment by prusnak** [comment]
> But I must be missing something _significant_ if RECEIVE address verification is difficult with a stateless device, but CHANGE address verification is trivial.

How exactly would an attack you have on your mind work? You assume that an attacker can craft a change address under their control but inputs are not under their control, right?

**Comment by achow101** [comment]
> The Trezor is stateless. It seems there is an implicit trust of the PSBT, w/o corresponding confirmation on a trusted display. And with HWI 2.1.1 the information displayed on the trusted display is reduced. If the software wallet coordinator is malware compromised, am I in a different situation on the Trezor than on the Coldcard/Keystone?

No. The Trezor can be provided with co-signer xpubs and the threshold for each multisig input and output. It can detect change by checking whether the multisig policies are identical between the inputs and a particular output. It verifies that the multisig matches the inputs and outputs by computing the expected scripts from it and checking against what is provided for those inputs and outputs.

If the host is compromised, the attacker could provide incorrect xpubs or threshold, which would only cause the scripts computed from the multisig to mismatch, and so the Trezor would not sign (or it would make an invalid signature).

**Comment by Francisco-DAnconia** [comment]
> It verifies that the multisig matches the inputs and outputs by computing the expected scripts from it and checking against what is provided for those inputs and outputs.

Thanks. I think I'm grasping this now. Let me re-phrase and attempt to answer my misconceptions. (Please let me know if I've got it or not - Thx)

The PSBT contains an input (UTXO) which must meet certain requirements (redeemScriptHash preimage, signatures) to spend. This requires the leaf public keys derived from the XPUBs and a quorum of signatures. These same XPUBs can generate the public keys for the CHANGE address. Thus a hardware device can corroborate the genuine origin of the CHANGE output based on the inputs (Which is why Michael says this is "trivial for any decently written hardware wallet to handle automatically in software." or as prusnak says the address is hidden when generated by the same keys as the input)

That is, there is nothing inherent in the nature of generating RECEIVE addresses versus CHANGE addresses from XPUBs that makes one more secure. It is all in the context of usage. 

CHANGE addresses are used in the context of a transaction, where their veracity is ensured by the input requirements (protected by hash collisions & discrete log problem). RECEIVE addresses are confirmed only by precautions taken by the user in choosing what sources to trust.

So wrt CHANGE addresses, It would seem I'm just as secure on the Trezor as I am on the Coldcard/Keystone (where MS wallets are registered).

Or maybe one could say the registering multi-signature wallets on hardware devices adds a very small extra check (maybe mostly in the UI), the real protection is the transaction input.

**Comment by Francisco-DAnconia** [comment]
> How exactly would an attack you have on your mind work? You assume that an attacker can craft a change address under their control but inputs are not under their control, right?

I'm curious if this attack is currently handled and/or thwarted:

What if the malware crafted the transaction such that the INPUT and CHANGE address were under the control of the same XPUBs. But the attacker modified the CHANGE address index to something bizarre, routing the change to an address index somewhere among the 4 billion possibilities.  Then a ransom follows.
