### ISSUE TITLE
Failure to cleanup temporary directory on crash

### ISSUE THREAD

**Issue by craigraw** [bitcoin-core/HWI#621]
When HWI experiences a crash (which can happen for example when Ledger Live is also running), pyinstaller fails to delete the temporary directory it creates when expanding `hwi` into a directly executable form. A couple of Sparrow users have reported that if executed multiple times in this situation, the `tmp` directory gradually fills up with 50Mb folders that look like `_MEIxxxxxx`. 

As I noted in https://github.com/sparrowwallet/sparrow/issues/629, this is a known (and old) [issue in pyinstaller](https://togithub.com/pyinstaller/pyinstaller/issues/2379) that has only very recently [been fixed](https://togithub.com/pyinstaller/pyinstaller/pull/6923). I'm opening this issue to track an update to the pyinstaller dependency in HWI.

Fwiw, I still believe that a `--onedir` build for HWI makes more sense however, particularly wrt MacOS (see #327) but also in general since expanding 50Mb folders on every invocation does not seem very efficient :) I have been using this approach for some years now on MacOS and it has proven to be preferable IMHO, at least for application developers.

**Comment by prusnak** [comment]
> [issue in pyinstaller](https://togithub.com/pyinstaller/pyinstaller/issues/2379) that has only very recently [been fixed](https://togithub.com/pyinstaller/pyinstaller/pull/6923).

It seems the issue was fixed in a PR that was merged 7 days ago, while the latest pyinstaller 5.2 release is 10 days old. I guess we need to wait for 5.3 release?

**Comment by craigraw** [comment]
Pyinstaller 5.3 has now been released, and includes fixes for this issue on both POSIX and Windows platforms: https://pyinstaller.org/en/v5.3/CHANGES.html#id1

**Comment by prusnak** [comment]
It seems that pyinstaller 5.3 requires python 3.7. We could bump pyinstaller to `^5.3` in `pyproject.toml`, but we'd need to bump python from `^3.6` to `^3.7`. What do you think @achow101?
