### ISSUE TITLE
I don't have a Ledger, but it detects one

### ISSUE THREAD

**Issue by JavierRSobrino** [bitcoin-core/HWI#622]
I was redirected from Sparrow support. Doing this:

```
$ ./hwi enumerate
[{"type": "ledger", "model": "ledger_nano_s_simulator", "label": null, "path": "tcp:127.0.0.1:9999", "error": "Could not open client or get fingerprint information: ('0x0', 'Error in <DefaultInsType.GET_VERSION: 1> command', '')", "code": -13}]

```
It detects a Ledger, but I never had one, and of course it has never been connected to my computer. Also, I'm not aware I ever installed the Ledger Nano Emulator. 

So when I use Sparrow Wallet it is always showing this uncomfortable error:

![image](https://user-images.githubusercontent.com/6039997/179918126-3e9dde8a-8cae-4bd3-8342-1aab5b041e71.png)

Any idea why this is happening?

System: Debian Linux 11 amd64.

**Comment by JavierRSobrino** [comment]
Yes, I have a service in 9999, I changed the port of it and now there is not a problem. Thank you.

Anyway, isn't there a better way to detect if a service in port 9999 is a Trezor one or not?

**Comment by achow101** [comment]
The detection could probably be improved.
