### ISSUE TITLE
Ledger Nano S and X : `Ledger requires BIP 44 standard paths`

### ISSUE THREAD

**Issue by Szpoti** [bitcoin-core/HWI#623]
After upgrading HWI from **2.0.2** to **2.1.1** _(FTR, same story with **2.1.0**)_, our unit tests related to Ledgers fails and we can't use Ledger Nano X and S to send.

Our tests fails when we send the **display address command** as follows:
```
 "--device-path \"\\\\?\\hid#vid_2c97&pid_1011&mi_00#7&f5b6544&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}\" --device-type \"ledger_nano_s\" displayaddress --path m/84h/0h/0h --addr-type wit"
 ```
and we get back the following response:
```
"{\"error\": \"Ledger requires BIP 44 standard paths\", \"code\": -7}\r\n"
```

Before the new releases, there was no problem with either the tests or sending.
For testing purposes, I replaced the path with `m/44h/0h/0h` on all three of the mentioned releases: **2.0.2** worked with `44` and `84`, the other releases fails the same way with both.

_Firmwares: latest `2.1.0` on Nano S and latest `2.0.2` on X. Bitcoin app version latest `2.0.6`_

**Comment by achow101** [comment]
On the ledger, are you using the Bitcoin app or the Bitcoin Testnet app?

**Comment by Szpoti** [comment]
The Bitcoin app. For the unit tests, the network is also set to `MainNet`.

**Comment by Szpoti** [comment]
**Update:** 
After following the steps to install the Bitcoin Testnet app, I was able to send on TestNet with Ledger with `AccountKeyPath: "84'/1'/0'"`, thats great! 🙏
So I assume maybe the problem is with the command above?

**Comment by adamPetho** [comment]
Sorry guys, the HWI is fine. Our tests were a bit out-dated.
