### ISSUE TITLE
Unusual P2SH derivation path causes signing on Trezor to fail

### ISSUE THREAD

**Issue by craigraw** [bitcoin-core/HWI#624]
Unchained Capital uses two unusual derivation paths when creating their standard P2SH 2-of-3 multisig wallets: `m/45'/0/0/0` and `m/45'/0'/0'/0`. These derivation paths cause HWI to return an error when attempting to sign with a Trezor. It appears this is new behaviour as of HWI 2.1.0 (it did not occur in previous versions).

To reproduce this, I created a multisig P2SH wallet with a Trezor as one of the signers, wallet descriptor as follows:
```
sh(sortedmulti(2,[c3591455/45h/0/0/0]tpubDErVNgpDZVndkCfPCANKaba95X4cBy4ieJTD7KmrmwbWUpmoSnyXBbw8yMnPySSLmuSSQDvKnaxeawu5Z7ay8EX6uewFnP26KfafTZ2rDBf/<0;1>/*,[ca9a2b19/45h/0/0/0]tpubDFU47kwMQqhh5GZmo5eP7CA68TaxtymGFsrgHNSfr3frVGcFKhcLxVnWV5XeHTbBXoUr3C2Eb9kNNqHPuXekPjcTTvdoqFrLtod4Z5N2apX/<0;1>/*))#stpamxtd
```

Attempting to sign with the Trezor using HWI results in the following error: 
`DataError: Multisig field provided but not expected.` 

I see this error text is generated by the Trezor firmware. The PSBT I was attempting to sign as follows:
```
cHNidP8BAHICAAAAAebA8z/RmQPLAgsN7zQUNCfMDCY0HBfGS5Da22CvGnfCAQAAAAD9////AsERAAAAAAAAFgAUZ+/SZu0/MnKKrqvmNsu5woaKAmK+DgAAAAAAABepFOUJ5ZfKAcojUmEo+pkDu8WeU9Dkh/NBIwBPAQQ1h88E1FWvhwAAAABx093CJKJO2rIKBJGi0OnHSFK0ZiB7D/VLOqLF842JIQL4MkiTlFF8JBb2/dyC2Q6Xns8Z6E4ZQsIXP63CI9tRkRTKmisZLQAAgAAAAAAAAAAAAAAAAE8BBDWHzwSA6SQ7AAAAABC7em5gh2yW9nmKt9rIr51/qKo1hcskuRaZxl8d3X5aAkmF9ugKiObVRw+MIpJw0tg7RLwh+9N35342dLhO3GAgFMNZFFUtAACAAAAAAAAAAAAAAAAAAAEAcgIAAAAB84o3aqcz7Qyy36z30GGG60N+0KvZz7yuSmZbsHrGZEwBAAAAAP7///8CW+QPAAAAAAAWABS0Xmkd4ROVjWRaLN43vC3zFZV3PhAnAAAAAAAAF6kUOVOqrknZCk+RdAp3h4Zwj0Pm60KH8EEjAAEDBAEAAAABBEdSIQLXZNH/vR5DTH5bNp5aLjlkTWmngdqaEsw7BJooqZRCByEDPCSTkW5TI37C6PLv9LHsNIlowndzc4h+mbhGO0Mh+kNSriIGAzwkk5FuUyN+wujy7/Sx7DSJaMJ3c3OIfpm4RjtDIfpDHMqaKxktAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAiBgLXZNH/vR5DTH5bNp5aLjlkTWmngdqaEsw7BJooqZRCBxzDWRRVLQAAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAEdSIQMBIXKdDxFTwBSYrNsWKLR1hNYVVcZff75xXJH9cAtqqCEDNu00Oxx4Ta7EnWpxDoqg7SX1hMm1Wq+4JAI60ekWtsdSriICAwEhcp0PEVPAFJis2xYotHWE1hVVxl9/vnFckf1wC2qoHMqaKxktAACAAAAAAAAAAAAAAAAAAQAAAAAAAAAiAgM27TQ7HHhNrsSdanEOiqDtJfWEybVar7gkAjrR6Ra2xxzDWRRVLQAAgAAAAAAAAAAAAAAAAAEAAAAAAAAAAA==
```

I confirmed that the same Trezor signs without problems when using the standard BIP45 P2SH derivation path of `m/45'`.

**Comment by prusnak** [comment]
@matejcik any ideas?

**Comment by matejcik** [comment]
This would happen if HWI selected wrong script type. Multisig is supported for `MULTISIG`, `P2SHSEGWIT` and `SEGWIT`. That leaves `ADDRESS` and `TAPROOT` as the wrong choices.

**Comment by matejcik** [comment]
more specifically, BIP45 aka P2SH multisig should use the `MULTISIG` script type. My guess is HWI is not recognizing the nonstandard paths as BIP45 and defaults to `ADDRESS` script type?

**Comment by prusnak** [comment]
Ah, this is probably related to https://github.com/trezor/trezor-firmware/issues/1526 (Trezor does not support BIP67 sortedmulti). 

@craigraw does it work if you use `sh(multi(...))` ?

**Comment by craigraw** [comment]
> @craigraw does it work if you use sh(multi(...)) ?

No, that produced the same result, but then again it would not change the PSBT. 

Incidentally, the descriptor is used when asking HWI to display an address using the `--desc` parameter. This fails with any P2SH path I have tried, for example the one below, with the error `No path supplied matched device keys`:
```
sh(multi(2,[ca9a2b19/45h]tpubD9kVtxWQHyTE3DEG4rHeNSdddXYgo75iffApXxLj5rXHgKkuhmszHaBhfYBPN1VsKsmaXimbNitufTHz8pBGQdxa1xRA2pr19bST3SacU1F/0/1,[c3591455/45h]tpubD9hQXa4R83w6oD6hFVkaBeGdJvTUkpMRHtS7N1h8f7vV4AjpxncWiqBp6K7WFoFEB9uffQvWoLDsGvNRP5FnCXTviB5LaeqSh1ihBAHfMVD/0/1))
```

Another P2WSH multisig wallet I tried though worked without errors, the Trezor displaying the address. 

The above is true regardless of whether using `multi` or `sortedmulti`

**Comment by achow101** [comment]
You are certain that the difference is only in the derivation path?

I suspect this might be an issue with all p2sh multisigs regardless of derivation path as it looks like when we prepare the outputs for multisig change detection, we are not setting the type to `MULTISIG`. Rather it defaults to `ADDRESS` for p2sh. With segwit, we are setting `WITNESS` and `P2SHSEGWIT` independently of the multisig, and those are acceptable values for a multisig output type.

**Comment by craigraw** [comment]
> You are certain that the difference is only in the derivation path?

Yes - I am able to get the Trezor to sign successfully with the following wallet:
```
sh(sortedmulti(2,[c3591455/45h]tpubD9hQXa4R83w6oD6hFVkaBeGdJvTUkpMRHtS7N1h8f7vV4AjpxncWiqBp6K7WFoFEB9uffQvWoLDsGvNRP5FnCXTviB5LaeqSh1ihBAHfMVD/<0;1>/*,[ca9a2b19/45h]tpubD9kVtxWQHyTE3DEG4rHeNSdddXYgo75iffApXxLj5rXHgKkuhmszHaBhfYBPN1VsKsmaXimbNitufTHz8pBGQdxa1xRA2pr19bST3SacU1F/<0;1>/*))#n7qukuwg
```

The only difference in creating this wallet was the derivation paths used.

**Comment by achow101** [comment]
@craigraw Try #625

**Comment by craigraw** [comment]
Thanks, have posted my results there.
