### ISSUE TITLE
Trezor detection issues

### ISSUE THREAD

**Issue by minioff** [bitcoin-core/HWI#628]
Hi,

having issues with HWI on Ubuntu 18.04.6 LTS and Trezor T and HWI 2.1.1.

Observe:
```
/tmp/hwi-2.1.12097600960383665175.tmp --version
hwi-2.1.12097600960383665175.tmp 2.1.1


/tmp/hwi-2.1.12097600960383665175.tmp enumerate
Please confirm action on your Trezor device

** HERE PASSWORD IS ENTERED ON TREZOR **

ERROR:jade:Exception causing JadeAPI context exit.
ERROR:jade:<class 'TypeError'>
ERROR:jade:a bytes-like object is required, not 'str'
  File "hwilib/devices/jade.py", line 542, in enumerate
  File "hwilib/devices/jadepy/jade.py", line 185, in get_version_info
  File "hwilib/devices/jadepy/jade.py", line 159, in _jadeRpc
  File "hwilib/devices/jadepy/jade.py", line 653, in make_rpc_call
  File "hwilib/devices/jadepy/jade.py", line 632, in read_response
  File "hwilib/devices/jadepy/jade.py", line 604, in read_cbor_message
WARNING:jade:Draining interface...
WARNING:jade-device:1 Ubuntu-4ubuntu0.7

** THERE IS ABOUT 1 MINUTE WAIT TIME BEFORE NEXT LINE SHOWS UP **

WARNING:jade-device:
[{"type": "trezor", "path": "webusb:001:3", "label": "label_is_here", "model": "trezor_t", "needs_pin_sent": false, "needs_passphrase_sent": false, "fingerprint": "fp_is_here"}]
```

So it seems like two issues:

- Device detected as Jade ?
- It takes about 1 minute or more to get a response

Tested different cable, different usb port, different hw wallet (also model t). Do not see any issues with bridge, trezord or trezor suite.

**Comment by prusnak** [comment]
Honestly, this seems like the Jade code being the culprit interrupting the standard Trezor flow.

@achow101 Is there a way how to turn off support of a particular HW wallet at start? Maybe via `--skip-jade` switch or something like that.


// cc @JamieDriver

**Comment by JamieDriver** [comment]
I'm guessing the trezor has already enumerated ok, but then the enumerate loop moves onto jade ?
```
ERROR:jade:a bytes-like object is required, not 'str'
  File "hwilib/devices/jade.py", line 542, in enumerate
...
```
This is where the code is probing for the test jade simulator by trying to connect to the simulator port, `tcp:127.0.0.1:2222`.  
It would appear that maybe there is something running on this port ?  
Saying that, everything inside 'test for simulator' is supposed to catch any errors and just ignore/continue.

Maybe we need to ignore simulators by default, and only probe for them if a certain flag is set (which the tests would set) ?

**Comment by JamieDriver** [comment]
Yeah, that may be the simplest option!  Will look into it asap.

**Comment by JamieDriver** [comment]
Jade master branch updated to run simulator on 30121 - hwi test client updated in #645

**Comment by prusnak** [comment]
@minioff please reopen if you still encounter the issue
