### ISSUE TITLE
Can't scan for hardware wallets in Sparrow wallet

### ISSUE THREAD

**Issue by Morning24** [bitcoin-core/HWI#652]
Sparrow isn't able to scan for hardware wallets. If the 'scan'-button is hit Sparrow shows 'scanning' and nothing else happens.
Problem is the same with BitBox02 and Ledger Nano S, both hardware wallets work fine with their native software.
Due to a successful test on another Laptop it seems to be a problem of the specific combination of Sparrow wallet and my (self build) computer.
All softwares are up to date (I run on Windows 10 home), I tested with and without USB-cable. The settings of my pc and the tested laptop (also W10 home) are identical (defender/system security...), no problems in device-manager.

In the Sparrow Wallet telegram channel someone instructed me to delete hwi folder -> no change.
Then I was supposed to run 'hwi-xxx enumerate' on command line in hwi folder but the cursor only jumps in the next row and stays there blinking.
He said that that's the problem, something on my system appears to be hanging when queried. I disconnected all USB-peripherals except keyboard and mouse, deleted hwi folder again and gave it another try -> same as before.

Something seems to prevent hwi from scanning for USB devices...

**Comment by prusnak** [comment]
> Then I was supposed to run 'hwi-xxx enumerate' on command line in hwi folder but the cursor only jumps in the next row and stays there blinking.

Press Ctrl+C when the cursor jumps in the next row and stays there blinking. Then past the output here.

**Comment by Morning24** [comment]
> Press Ctrl+C when the cursor jumps in the next row and stays there blinking. Then past the output here.

![cmd_hwi](https://user-images.githubusercontent.com/117046483/205722324-9b3fa4b3-1f12-4b87-b36a-363fb140f586.jpg)

When I press Ctrl+C (copy?) and want to paste it in notepad or here there is no output. The paste option is shown but it contains no data...

**Comment by prusnak** [comment]
> When I press Ctrl+C (copy?)

Hm, I meant Ctrl+C as in break. Maybe Ctrl+Break works on Windows?

**Comment by Morning24** [comment]
Oh, ok. Ctrl+C changes nothing, Ctrl+Break results in:
^C

**Comment by achow101** [comment]
My guess is something is running on one of the simulator ports and HWI is just waiting for a response that it never receives. Do you have anything that's listening on ports 2222, 21324, 11044, or 9999?

What is the output of `hwi --debug enumerate`?

**Comment by prusnak** [comment]
> Do you have anything that's listening on ports 2222, 21324, 11044, or 9999?

It almost sounds like it would be great idea to not enumerate emulators by default (which is what 99.9% users don't need) and only deal with emulators when `--emulator` option is provided. Created an issue here: https://github.com/bitcoin-core/HWI/issues/653

**Comment by Morning24** [comment]
> Do you have anything that's listening on ports 2222, 21324, 11044, or 9999?

Ehm, I'm not an IT pro- how can I figure it out, pls?

> What is the output of `hwi --debug enumerate`?

DEBUG:ledgercomm:=> b001000000

That's all, the cursor stays in the next row blinking.
