### ISSUE TITLE
Don't enumerate emulators unless `--emulator` flag is provided

### ISSUE THREAD

**Issue by prusnak** [bitcoin-core/HWI#653]
See https://github.com/bitcoin-core/HWI/issues/652#issuecomment-1340149342 for motivation.

And https://github.com/bitcoin-core/HWI/issues/628.

I think there are other issues reported here which are caused by stalled enumerations where there is something else than an emulator running on a scanned port.

**Comment by craigraw** [comment]
+1 on this - it's a common problem that is often time-consuming to diagnose.

**Comment by achow101** [comment]
Since that would be a breaking change to the interface, would it be acceptable to do the inverse - a `--no-emulators` option to explicitly ignore emulators?

**Comment by craigraw** [comment]
Yes, that would work for me.

**Comment by prusnak** [comment]
Since emulators are only used by developers and not regular users, I would be OK with changing the default. It would be also the most straightforward way how to fix weird issues easily in the whole ecosystem.

However, if you feel strongly about not changing it, I am fine with the --no-emulators option. But we would need to reach out to all downstream projects (wallets that use HWI), to add the option into their stack.

**Comment by achow101** [comment]
Mainly I don't want to change the default behavior since SemVer (which I'm trying to follow) requires bumping the major version for that.

**Comment by prusnak** [comment]
> Mainly I don't want to change the default behavior since SemVer (which I'm trying to follow) requires bumping the major version for that.

So why not bump the major version then?

**Comment by achow101** [comment]
> So why not bump the major version then?

I suppose I could. Just feels weird to do that when there's nothing else going on.

**Comment by prusnak** [comment]
> I suppose I could. Just feels weird to do that when there's nothing else going on.

Yes. That is SemVer :-)
