### ISSUE TITLE
Ledger Nano S Plus Detection Isues

### ISSUE THREAD

**Issue by Exym15** [bitcoin-core/HWI#656]
Hi,
having issues with HWI on Linux Mint 21 Cinnamon 5.4.8 - 
**HWI before opening the BTC application in my LEDGER**
```
./hwi.py enumerate
WARNING:jade:No module named 'hwilib.devices.jadepy.jade_ble'
WARNING:jade:BLE scanning/connectivity will not be available
[{"type": "ledger", "model": "ledger_nano_s_plus", "label": null, "path": "1-2:1.0", "error": "Could not open client or get fingerprint information: Ledger is not in either the Bitcoin or Bitcoin Testnet app", "code": -3}]
```

**HWI after opening the BTC application in my LEDGER**
```
./hwi.py enumerate
WARNING:jade:No module named 'hwilib.devices.jadepy.jade_ble'
WARNING:jade:BLE scanning/connectivity will not be available
[{"type": "ledger", "model": "ledger_nano_s_plus", "label": null, "path": "1-2:1.0", "error": "Could not open client or get fingerprint information: unsupported hash type ripemd160", "code": -7}]

```
**I have previously observed all possible similar solutions and they do not work, what am I doing wrong?**

**Comment by achow101** [comment]
I suspect this is a result of openssl removing ripemd160 so python's hashlib is no longer able to produce ripemd160 hashes. Resolving this has been on my list of things to do, but haven't actually worked on a solution yet, see #305.

To confirm, if you do `openssl dgst -list`, do you see `ripemd160` in the list? If not, then that is the source of this issue. The only way to resolve this is to use an older version of openssl that still has ripemd160 and make sure that your python is compiled against it.

**Comment by Exym15** [comment]
I have a couple of weeks working on linux, excuse my ignorance. Would it be better to change distribution and try another?
`openssl dgst -list
Supported digests:
-blake2b512                -blake2s256                -md4                      
-md5                       -md5-sha1                  -ripemd                   
-ripemd160                 -rmd160                    -sha1                     
-sha224                    -sha256                    -sha3-224                 
-sha3-256                  -sha3-384                  -sha3-512                 
-sha384                    -sha512                    -sha512-224               
-sha512-256                -shake128                  -shake256                 
-sm3                       -ssl3-md5                  -ssl3-sha1                
-whirlpool                 
`

**Comment by achow101** [comment]
It's listed there.. but I think that's because it is a "legacy" function so not actually removed yet?

Can you try `openssl speed ripemd160`?

According to [this StackOverflow answer](https://stackoverflow.com/a/72508879), it can be enabled with a configuration file.

> Would it be better to change distribution and try another?

Probably not. Recent distributions are likely to be upgrading their openssl versions to the recent releases which will have the same issue.

**Comment by achow101** [comment]
Apparently it was [added back](https://www.openssl.org/blog/blog/2022/10/18/rmd160-and-the-legacy-provider/), so make sure your openssl version is at least 3.0.7.

**Comment by Exym15** [comment]
Hello again, thanks for the help. The solution was to modify the openssl and add the following lines.

> According to [this StackOverflow answer](https://stackoverflow.com/a/72508879), it can be enabled with a configuration file.

`openssl_conf = openssl_init

[openssl_init]
providers = provider_sect

[provider_sect]
default = default_sect
legacy = legacy_sect

[default_sect]
activate = 1

[legacy_sect]
activate = 1`

Thank You!!

**Comment by Sjors** [comment]
Ubuntu 22.10 currently ships with OpenSSL 3.0.5 so this issue may be around for a while. Maybe we should check for it directly so the error is less cryptic?

**Comment by harding** [comment]
Just a note that I also seem to have just hit this OpenSSL issue (slightly different circumstances) and the workaround also worked for me (so far no obvious side-effects; `dig` continues to work).

Circumstance: running `hwi displayaddress` with a Trezor:

```
hwi -t trezor -d webusb:003:2 displayaddress --desc sh(wsh(sortedmulti(...)))#...

{"error": "unsupported hash type ripemd160", "code": -7}
```

For anyone else stumbling on this issue, note that this test returns "0" for everything when ripemd _isn't_ available:

> Can you try `openssl speed ripemd160`?
