### ISSUE TITLE
Why does HWI 0.5.0 have a fixed once_cell dependency version 1.14?

### ISSUE THREAD

**Issue by thibistaken** [bitcoin-core/HWI#668]
_I hope this is the right place to get some help on this. I spoke with the Tauri team but they couldn't help. Tried with BDK but no luck so far..._ 

I am building a desktop app with Rust using Tauri and BDK, which uses HWI. I tried to update to the latest version of BDK `0.27.0` but I get an error due to conflicting versions in the HWI Rust wrapper dependencies. The error message is below.

It looks like `BDK 0.27.0` requires `HWI 0.5.0` from [crates.io](https://crates.io/crates/hwi/0.5.0/dependencies), which requires exactly the `once_cell 1.14.0` crate. This version requirement in HWI conflicts with what Tauri currently requires on its LTS version (`1.2`), which is at least `once_cell 1.15.0`. 

Why does `HWI 0.5.0` require exactly version `=1.14` for once_cell? Why not `^1.14` instead? Would you have a way to fix this?

Thank you!

> [ERROR rust_analyzer::lsp_utils] cargo check failed:
> Cargo watcher failed, the command produced no valid metadata (exit code: ExitStatus(unix_wait_status(25856))):
>     Updating crates.io index
> error: failed to select a version for `once_cell`.
>     ... required by package `wry v0.22.0`
>     ... which satisfies dependency `wry = "^0.22"` of package `tauri-runtime-wry v0.12.0`
>     ... which satisfies dependency `tauri-runtime-wry = "^0.12.0"` of package `tauri v1.2.0`
>     ... which satisfies dependency `tauri = "^1.2"` of package `juno v0.0.0 (/Users/thibm/Documents/dev/Juno/src-tauri)`
> versions that meet the requirements `^1.15` are: 1.17.0, 1.17.1, 1.16.0, 1.15.0
> 
> all possible versions conflict with previously selected packages.
> 
>   previously selected package `once_cell v1.14.0`
>     ... which satisfies dependency `once_cell = "=1.14"` of package `hwi v0.5.0`
>     ... which satisfies dependency `hwi = "^0.5"` of package `bdk v0.27.0`
>     ... which satisfies dependency `bdk = "^0.27.0"` of package `juno v0.0.0 (/Users/thibm/Documents/dev/Juno/src-tauri)`
> 
> failed to select a version for `once_cell` which could resolve this conflict

**Comment by prusnak** [comment]
The correct repo for rust-hwi is https://github.com/bitcoindevkit/rust-hwi

**Comment by thibistaken** [comment]
Noted. Will move the issue over there. Thank you.

**Comment by thibistaken** [comment]
Moved to https://github.com/bitcoindevkit/rust-hwi/issues/72
