### ISSUE TITLE
cbor 1 is old, unmaintained, upstream repo is gone, incompatible with newer Python versions

### ISSUE THREAD

**Issue by jjakob** [bitcoin-core/HWI#678]
cbor 1 is unmaintained, the upstream repository is gone:  https://bitbucket.org/bodhisnarkva/cbor , only lists compatibility up to Python 3.5, has been removed from Gentoo: https://gitweb.gentoo.org/repo/gentoo.git/commit/?id=b7e905a90bc51d70655ed0f344e04fb2c7d36c72
The replacement is https://github.com/agronholm/cbor2 but I don't know how compatible it is.
cbor is used here: https://github.com/bitcoin-core/HWI/blob/43cc81d3af7e1de20fa8c92570d305440bb0a33b/hwilib/devices/jadepy/jade.py

**Comment by achow101** [comment]
@JamieDriver Since Jade is the only device that uses cbor, can the dependency be replaced with a maintained library?

**Comment by JamieDriver** [comment]
I'll take a  look ...

**Comment by JamieDriver** [comment]
Ok, with some v.minor tweaking I think it should all be good with the newer cbor2 dependency.  

What I will do then, is update the Jade API in the Jade repo and ensure all the tests pass etc. and that it continues working well for all 'manual' usage over the next dev/release cycle.  
All being well we'll include this change in the next Jade release, and once made I'll make an MR here to bump to that updated Jade API release and update the dependencies files.

**Comment by JamieDriver** [comment]
#710 raised to update the jade-api to a version using an actively-supported cbor dependency.
Apologies for the delay.
