### ISSUE TITLE
Base58 decode_check always returns invalid checksum

### ISSUE THREAD

**Issue by craigraw** [bitcoin-core/HWI#700]
As per title. Because the calculated checksum in https://github.com/bitcoin-core/HWI/blob/17d5643b9db240d4fbee3f1614e7e1aeade4e9ac/hwilib/_base58.py#L96-L98 uses the full result of the double sha256 and not just the first four bytes, the comparison to the received checksum always fails.

In https://github.com/bitcoin-core/HWI/commit/674cb08d6ffcecbf2502a05dd4371c1cfc8baa93 HWI switched to using it's own base58 implementation for the Bitbox02. This bug is now causing all attempts to sign a multisig PSBT to fail on the Bitbox02 using HWI 2.3.0 due to use of this function in https://github.com/bitcoin-core/HWI/blob/17d5643b9db240d4fbee3f1614e7e1aeade4e9ac/hwilib/devices/bitbox02.py#L425

cc @benma

**Comment by benma** [comment]
:facepalm: thanks for reporting. I guess I'll make a PR then. @achow101 would be nice to make a hotfix release afterwards.

**Comment by benma** [comment]
Made a PR https://github.com/bitcoin-core/HWI/pull/701. cc @achow101
