### ISSUE TITLE
Bitbox fails to sign PSBT

### ISSUE THREAD

**Issue by dr-orlovsky** [bitcoin-core/HWI#706]
Using new miniscript-supporting firmware https://github.com/digitalbitbox/bitbox-wallet-app/releases/tag/v4.39.0 bitbox fails to sign psbt (using command `hwi signtx`) and fails with following message:

```
Traceback (most recent call last):
  File "/home/orlovsky/repos/HWI/venv/bin/hwi", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/orlovsky/repos/HWI/venv/lib/python3.11/site-packages/hwilib/_cli.py", line 304, in main
    result = process_commands(sys.argv[1:])
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/orlovsky/repos/HWI/venv/lib/python3.11/site-packages/hwilib/_cli.py", line 280, in process_commands
    client = find_device(args.password, args.device_type, args.fingerprint, args.expert, args.chain)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/orlovsky/repos/HWI/venv/lib/python3.11/site-packages/hwilib/commands.py", line 148, in find_device
    devices = enumerate(password)
              ^^^^^^^^^^^^^^^^^^^
  File "/home/orlovsky/repos/HWI/venv/lib/python3.11/site-packages/hwilib/commands.py", line 117, in enumerate
    result.extend(imported_dev.enumerate(password, expert, chain))
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/orlovsky/repos/HWI/venv/lib/python3.11/site-packages/hwilib/devices/bitbox02.py", line 183, in enumerate
    client = Bitbox02Client(path)
             ^^^^^^^^^^^^^^^^^^^^
  File "/home/orlovsky/repos/HWI/venv/lib/python3.11/site-packages/hwilib/devices/bitbox02.py", line 272, in __init__
    hid_device.open_path(path.encode())
  File "hid.pyx", line 157, in hid.device.open_path
OSError: open failed
```

**Comment by benma** [comment]
This error means that the device is likely occupied by another connection. Close BitBoxApp and other things that could connect first.

By the way, miniscript policies will not work with HWI out of the box, as one has to send the miniscript policy to the BitBox02, which is not part of the PSBT and not part of the HWI API currently.

**Comment by prusnak** [comment]
udev rules

**Comment by dr-orlovsky** [comment]
> udev rules installed?

yes, the rest of BitBox API through HWI works as expected

> By the way, miniscript policies will not work with HWI out of the box, as one has to send the miniscript policy to the BitBox02, which is not part of the PSBT and not part of the HWI API currently.

Ok, I think this is the case why it is not working

**Comment by dr-orlovsky** [comment]
> Ok, I think this is the case why it is not working

But again, it is just a multisig, not timelocked, and on the previous version of firmware it was signing such PSBTs

**Comment by benma** [comment]
The PSBT has nothing to do with your issue. The error message you posted shows that the connection to the BitBox02 could not be made. That is before any signing would happen.

> This error means that the device is likely occupied by another connection. Close BitBoxApp and other things that could connect first.

Did you try that?

**Comment by dr-orlovsky** [comment]
You are right. The device still doesn't sign - but it is unrelated to HWI. Some other process was using it. Closing here and open issue in BitBox: https://github.com/digitalbitbox/bitbox02-firmware/issues/1125
