### ISSUE TITLE
Support Trezor Safe 3

### ISSUE THREAD

**Issue by craigraw** [bitcoin-core/HWI#713]
As per title. HWI currently reports
```
[{“type”: “trezor”, “path”: “webusb:001:1", “error”: “Could not open client or get fingerprint information: Unsupported Trezor model”, “code”: -13}]
```

**Comment by achow101** [comment]
cc @prusnak @matejcik

**Comment by prusnak** [comment]
> cc @prusnak @matejcik

I guess we need to update the hwi local copy of trezorlib to the latest.

**Comment by michalfeher** [comment]
> > cc @prusnak @matejcik
> 
> I guess we need to update the hwi local copy of trezorlib to the latest.

Do you have any time estimate?

**Comment by prusnak** [comment]
I think all we need to do is update file `hwilib/devices/trezorlib/models.py` with new contents from https://github.com/trezor/trezor-firmware/blob/main/python/src/trezorlib/models.py

Can you please do that @achow101 and prepare a new binary for @craigraw to test with?

**Comment by PeteClubSeven** [comment]
> I think all we need to do is update file `hwilib/devices/trezorlib/models.py` with new contents from https://github.com/trezor/trezor-firmware/blob/main/python/src/trezorlib/models.py
> 
> Can you please do that @achow101 and prepare a new binary for @craigraw to test with?

Hi, I did try doing this myself on my Mac and it doesn't seem to be a solution. Although my device is detected it fails to get the fingerprint information from my device:
```
[{"type": "trezor", "path": "webusb:001:1:3:1", "label": "My Trezor", "model": "trezor_safe 3", "needs_pin_sent": false, "needs_passphrase_sent": false, "error": "Could not open client or get fingerprint information: InvalidSession: Invalid session", "code": -13}]
```

**Comment by craigraw** [comment]
Tested 2.4.0-rc.1 on the Trezor Safe 3, no issues to report. Just waiting on the final 2.4.0 release now.
