### ISSUE TITLE
Documentation: Typo?

### ISSUE THREAD

**Issue by andreasgriffin** [bitcoin-core/HWI#717]
Hi
in https://github.com/bitcoin-core/HWI/blob/7fd2cead481197f88cad180757b5cf982eb0a0b1/hwilib/common.py#L41C1-L42
there is  `P2WPSH`. But should it not be `P2WSH` as defined in https://github.com/bitcoin/bips/blob/master/bip-0048.mediawiki ?

**Comment by brunoerg** [comment]
I think so. P2WSH/P2SH-P2WSH for scripts.
