### ISSUE TITLE
Trezor T can't sign >100 inputs

### ISSUE THREAD

**Issue by ndeet** [bitcoin-core/HWI#720]
One of our merchants reported that he can't sign >100 inputs with his Trezor T on our BTCPay Vault or a Sparrow wallet. But he can sign 700 inputs on Electrum, which looks like there is an issue with hwi, original report see [here](https://github.com/btcpayserver/BTCPayServer.Vault/issues/77)

The address types used are native segwit and wrapped segwit. Also not sure if this is only related to Trezor T. 

He also puts a $1500 bounty in BTC on the table if this gets fixed quickly, happy to collect and forward it to you or he directly to pays to an official hwi donation address. Disclaimer I can't verify or be sure he will stand by his word and pay up as he is anon, could totally not happen at all

**Comment by ndeet** [comment]
The user reported that it worked with 500 inputs on MacOS, so there seems to be only an issue with Windows.

**Comment by NicolasDorier** [comment]
This isn't really HWI fault, it seems that windows have an issue passing a parameter with too many chars. Maybe same issue on linux.

**Comment by NicolasDorier** [comment]
This is related to char limits on windows. Added feature request on  https://github.com/bitcoin-core/HWI/issues/723

**Comment by ndeet** [comment]
I forgot to update here but the user later also reported that MacOS has the same problem:
> Btw I got too excited because pre signing worked but today when the fees dropped I decided to confirm the tx and sign it. Once I did that (clicking on sign on the trezor). It got stuck at signing transaction on the trezor, and btcpay server says user refused to sign.

So likely affecting all platforms as you suggested in #723 maybe there is a way to pass data in a different way on all those platforms.

**Comment by NicolasDorier** [comment]
@ndeet probably a different issue for the "refused to sign" error.

**Comment by NicolasDorier** [comment]
I found out hwi has the proper feature to fix the windows issue. For the "refused to sign" error, taking a look at it now.

**Comment by NicolasDorier** [comment]
I couldn't reproduce on coldcard. It seems that the hwi process returns before Trezor T is done signing?

**Comment by AlphaTEsterUnited** [comment]
Dear Devs,

Windows and OSX indeed behave similarly. I'm unable to send any transaction with over 200 inputs using JADE, Trezor, and Ledger through the HWI implementation in Sparrow and BTCPay. It's important to note that the wallet is P2SH (Pay to Script Hash).

**Steps to reproduce:**
Attempt to send a transaction with over 200 inputs (for comparison, Electrum can consistently handle over 900). Two failure scenarios occur with Trezor:

1. In one scenario, pre-signing (loading transactions) is successful, but after confirming on the Trezor, BTCPay immediately displays "The user refused to sign the transaction," and the progress bar on the Trezor halts See screenshot:
![image](https://github.com/bitcoin-core/HWI/assets/157733777/c95da139-ec91-46b9-b0ac-cd512a7a2e84)

2. In the other scenario, nothing appears on the Trezor and the BTCPay server vault remains in the "signtx" state See screenshot:
![image](https://github.com/bitcoin-core/HWI/assets/157733777/abb7b317-9372-4247-9780-e9349747b32c)


Thank you for looking into this issue.

Is there anyway I can generate logs btw?

**Comment by divinationstar** [comment]
The same timeout issue also happens on Linux with 150+ inputs using a ledger nano x. Have not tried it with a Trezor. I imagine any merchant that handles lots of daily transactions will have the same problem. Either they zero out their wallet every 50-100 transactions or this needs to be fixed.

**Comment by achow101** [comment]
This seems to be a problem with BTCPayServer not using `--stdin` on all platforms.

**Comment by NicolasDorier** [comment]
There was two issues. First was the `--stdin`. This was fixed in 2.0.9.

But now, this is a different error, which seem to be happening across multiple OS.

@AlphaTEsterUnited can you try with Sparrow wallet if it also happen? If yes, then it is a hwi issue.
Please come on https://chat.btcpayserver.org/ and ping me. I'll ask achow to re-look into this once we are sure that it comes from hwi.

**Comment by NicolasDorier** [comment]
Meanwhile I opened on our repo https://github.com/btcpayserver/BTCPayServer.Vault/issues/78 until we manage to find the root cause.
