### ISSUE TITLE
[Feature Request] Add ability to pass cli arguments with stdin

### ISSUE THREAD

**Issue by NicolasDorier** [bitcoin-core/HWI#723]
It turns out that Windows has a limit to the number of chars in arguments to pass by using `CreateProcess` of 32767  chars. 

It would be nice if it was possible to pass those arguments via stdin instead. (ie, an interactive mode, but not limited to a few commands)

Especially, `signtx`'s PSBT.

Source: https://devblogs.microsoft.com/oldnewthing/20031210-00/?p=41553

Fix https://github.com/bitcoin-core/HWI/issues/720 (apparently it has a bounty)

**Comment by achow101** [comment]
Does the `--stdin` option not work?

**Comment by NicolasDorier** [comment]
how the fuck did I miss that... I looked for it. Trying this, but this probably solve the issue. Will report soon.

**Comment by NicolasDorier** [comment]
yeah works sorry for that
