### ISSUE TITLE
Windows thinks hwi.exe is a trojan

### ISSUE THREAD

**Issue by Sjors** [bitcoin-core/HWI#726]
I tried to test `hwi-2.4.0-windows-x86_64.zip` from the tag downloads, but Windows Security immediately quarantines it.

It says it detected "Trojan:Win32/Wacatac.B!ml".

**Comment by Sjors** [comment]
It has no issue with rc1

**Comment by craigraw** [comment]
Although normally I'd say this is the AV's problem (and not HWI's), practically it's causing a lot of problems and false positive reports don't seem to be having much impact. Virustotal [still lists the same number of vendors](https://www.virustotal.com/gui/file/2541b1e7ada2640e26ef7ce3491585e1788ad9be68d4ac5e818d38d23a4a9cab/detection) flagging this as a virus (28/73).

@achow101 is there any chance of a 2.4.1 release? Ideally I would like to see https://github.com/bitcoin-core/HWI/issues/653 implemented - it causes consistent issues (had another report today) and the fix seems practical.

**Comment by BenoitCharraBC** [comment]
Having the same problem. Is this a real threat or a problem with the new release of Sparrow?

**Comment by Sjors** [comment]
Probably neither, HWI is independent of Sparrow. But ignoring such warnings can be dangerous, since next time there might be a real issue.

**Comment by achow101** [comment]
Published 3.0.0-rc.1 which seems to not be flagged as badly as 2.4.0 in virustotal. Hopefully the final release will also be fine, although I have no idea what they're flagging on.
