### ISSUE TITLE
Any plan to support QA based AirGap Bitcoin hardware wallet ?

### ISSUE THREAD

**Issue by aaronisme** [bitcoin-core/HWI#734]
Hi, Currently on the Bitcoin Community, There is some hardware wallet (like ColdCard Q, Keystone Bitcoin wallet and foundation wallet) are focused on the air-gapped mode which use QA Code for the data transmission.  Does the HWI have any plan to support these types of device?

**Comment by achow101** [comment]
No

**Comment by aaronisme** [comment]
OK, Thanks for sharing the info
